-- local plugin_name = "nvim-web-devicons"
--
-- local function loading()
--   require(plugin_name).setup({
--     -- your personnal icons can go here (to override)
--     -- DevIcon will be appended to `name`
--     override = {},
--     -- globally enable default icons (default to false)
--     -- will get overriden by `get_icons` option
--     default = true,
--   })
-- end
--
-- loading()
