#!/bin/sh

# get the list of staged files
files=$(git diff --cached --name-only --diff-filter=ACM)

git stash -k
bun x @secretlint/quick-start  $(git diff --name-only --cached)
git add $files
git stash pop
