#!/bin/sh

secretlint="@secretlint/quick-start"
files=$(git ls-files)

if [ -z "$files" ]; then
  exit 0
fi

if command -v bun >/dev/null 2>&1; then
  bun x $secretlint $files
elif command -v pnpm >/dev/null 2>&1; then
  pnpm dlx $secretlint $files
else
  npx $secretlint $files
fi

