#!/bin/sh

secretlint="@secretlint/quick-start"
files=$(git ls-files)

if command -v bun >/dev/null 2>&1; then
  bun x $secretlint $files
elif command -v deno >/dev/null 2>&1; then
  deno run -A "npm:$secretlint" $files
else
  npx $secretlint $files
fi

