# Lefthook configuration for dotfiles repository
# https://github.com/evilmartians/lefthook

pre-commit:
  commands:
    fmt:
      glob: "*.{nix,lua,json,json5}"
      run: nix run .#fmt -- {staged_files}
      stage_fixed: true
      skip:
        - rebase
        - merge

post-commit:
  commands:
    nix-apply:
      run: |
        if git diff HEAD^..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/|aqua/aqua.yaml)'; then
          echo "🔧 Nix configuration changed. Applying changes..."
          nix run .#switch
        fi
      skip:
        - rebase
        - merge

post-checkout:
  commands:
    nix-apply:
      run: |
        # Skip if just restoring files (flag=0)
        # post-checkout receives: $1=prev HEAD, $2=new HEAD, $3=flag
        if [ "${LEFTHOOK_GIT_POST_CHECKOUT_FLAG:-1}" = "0" ]; then
          exit 0
        fi
        if git diff HEAD@{1}..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/|aqua/aqua.yaml)'; then
          echo "🔧 Nix configuration changed. Applying changes..."
          nix run .#switch
        fi
      skip:
        - rebase
        - merge

post-merge:
  commands:
    nix-apply:
      run: |
        if git diff HEAD@{1}..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/|aqua/aqua.yaml)'; then
          echo "🔧 Nix configuration changed. Applying changes..."
          nix run .#switch
        fi
      skip:
        - rebase
        - merge
