tap "apple/apple", "http://github.com/apple/homebrew-apple"
tap "artginzburg/tap"
tap "clojure/tools"
tap "danielbayley/alfred"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "kphrx/personal"
tap "kyoh86/tap"
tap "libsql/sqld"
tap "masutaka/tap"
tap "nikitabobko/tap"
tap "opencode-ai/tap"
tap "sdkman/tap"
tap "tursodatabase/tap"
brew "libpng"
brew "little-cms2"
brew "aom"
brew "bluetoothconnector"
brew "boost"
brew "freetype"
brew "fontconfig"
brew "glib"
brew "cairo"
brew "fribidi"
brew "gdk-pixbuf"
brew "graphite2"
brew "harfbuzz"
brew "libavif"
brew "pango"
brew "librsvg"
brew "chafa"
brew "cmigemo"
brew "libyaml"
brew "cocoapods"
brew "gcc"
brew "dlib"
brew "openjpeg"
brew "leptonica"
brew "tesseract"
brew "ghostscript"
brew "epstool"
brew "libgit2"
brew "folly"
brew "fizz"
brew "wangle"
brew "xxhash"
brew "fbthrift"
brew "fb303"
brew "libogg"
brew "flac"
brew "frei0r"
brew "libtasn1"
brew "unbound"
brew "gnutls"
brew "lame"
brew "libass"
brew "libbluray"
brew "libsamplerate"
brew "libvorbis"
brew "mpg123"
brew "libsndfile"
brew "libsoxr"
brew "libssh"
brew "libvidstab"
brew "libvpx"
brew "sdl2"
brew "zeromq"
brew "ffmpeg@4"
brew "open-mpi"
brew "fftw"
brew "fig2dev"
brew "fltk"
brew "gd"
brew "gl2ps"
brew "glfw"
brew "glpk"
brew "libusb"
brew "libcerf"
brew "qt"
brew "gnuplot"
brew "gobject-introspection"
brew "gperftools"
brew "libde265"
brew "shared-mime-info"
brew "libheif"
brew "graphicsmagick"
brew "gts"
brew "graphviz"
brew "hdf5"
brew "icoutils"
brew "libomp", link: true
brew "imagemagick"
brew "lapack"
brew "openjdk"
brew "leiningen"
brew "libcroco"
brew "libepoxy"
brew "libffi"
brew "libusbmuxd"
brew "libimobiledevice"
brew "libsixel"
brew "libslirp"
brew "libspiro"
brew "libtermkey"
brew "libuninameslist"
brew "libuv"
brew "libzip"
brew "llvm"
brew "media-info"
brew "metis"
brew "msgpack"
brew "zlib"
brew "mysql-client"
brew "utf8proc"
brew "pam-reattach"
brew "plotutils"
brew "poppler"
brew "portaudio"
brew "portmidi"
brew "protobuf"
brew "pyqt"
brew "pyqt@5"
brew "python@3.11"
brew "python@3.9"
brew "qhull"
brew "qrupdate"
brew "qscintilla2"
brew "rlwrap"
brew "screenresolution"
brew "smartmontools"
brew "suite-sparse"
brew "sundials"
brew "swift-format"
brew "swift-sh"
brew "switchaudio-osx"
brew "ta-lib"
brew "typos-lsp"
brew "veclibfort"
brew "artginzburg/tap/sudo-touchid"
brew "kyoh86/tap/git-branches"
brew "kyoh86/tap/git-vertag"
cask "aerospace"
cask "alfred"
cask "alt-tab"
cask "appcleaner"
cask "arc"
cask "audacity"
cask "background-music"
cask "balenaetcher"
cask "blackhole-16ch"
cask "blu-ray-player-pro"
cask "bluesnooze"
cask "cloudflare-warp"
cask "cyberduck"
cask "db-browser-for-sqlite"
cask "dbeaver-community"
cask "deskpad"
cask "discord"
cask "font-line-seed-jp"
cask "font-udev-gothic"
cask "font-udev-gothic-nf"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "hammerspoon"
cask "imageoptim"
cask "jetbrains-toolbox"
cask "jettison"
cask "jupyter-notebook-viewer"
cask "kap"
cask "karabiner-elements"
cask "keycastr"
cask "licecap"
cask "lulu"
cask "maestral"
cask "microsoft-auto-update"
cask "min"
cask "monitorcontrol"
cask "obs"
cask "obsidian"
cask "ollama"
cask "openvpn-connect"
cask "orbstack"
cask "piphero"
cask "processing"
cask "qlvideo"
cask "quitter"
cask "raspberry-pi-imager"
cask "raycast"
cask "sdformatter"
cask "secretive"
cask "shortcat"
cask "shottr"
cask "skim"
cask "ssh-tunnel-manager"
cask "stats"
cask "suspicious-package"
cask "symboliclinker"
cask "syncthing"
cask "touch-bar-simulator"
cask "transmission@nightly"
cask "visual-studio-code"
cask "vlc"
cask "wezterm"
cask "xquartz"
cask "zed"
cask "zerotier-one"
cask "zoom"
mas "Accelerate", id: 1459809092
mas "Actions", id: 1586435171
mas "AdGuard for Safari", id: 1440147259
mas "Aiko", id: 1672085276
mas "Amphetamine", id: 937984704
mas "Be Focused", id: 973134470
mas "Blackmagic Disk Speed Test", id: 425264550
mas "BlockComment", id: 1246672247
mas "Clean", id: 418412301
mas "Color Picker", id: 1545870783
mas "Command X", id: 6448461551
mas "Consent-O-Matic", id: 1606897889
mas "CotEditor", id: 1024640650
mas "DevCleaner", id: 1388020431
mas "Document Generator", id: 1437883178
mas "Download Shuttle", id: 847809913
mas "DuckDuckGo Privacy for Safari", id: 1482920575
mas "Final Cut Pro", id: 424389933
mas "FocusRecorder", id: 6446467176
mas "Gemini 2", id: 1090488118
mas "Gifski", id: 1351639930
mas "GIPHY CAPTURE", id: 668208984
mas "Grammarly for Safari", id: 1462114288
mas "Hex Fiend", id: 1342896380
mas "Hush", id: 1544743900
mas "iHosts", id: 1102004240
mas "Keepa - Price Tracker", id: 1533805339
mas "Keynote", id: 409183694
mas "Keyword Search", id: 1558453954
mas "Kindle", id: 302584613
mas "LadioCast", id: 411213048
mas "LanguageTranslator", id: 1218781096
mas "Leftovers", id: 6746164364
mas "LINE", id: 539883307
mas "LLMFarm", id: 0
mas "Mapture", id: 1671995907
mas "Mathpix Snipping Tool", id: 1349670778
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "NamingTranslator", id: 1218784832
mas "Pages", id: 409201541
mas "PicGIF Lite", id: 844918735
mas "PiPifier", id: 1160374471
mas "Refined GitHub", id: 1519867270
mas "Screegle", id: 1591051659
mas "Seashore", id: 1448648921
mas "Sequel Ace", id: 1518036000
mas "Shareful", id: 1522267256
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Spaced", id: 1666327168
mas "Spark", id: 1176895641
mas "Speedtest", id: 1153157709
mas "Squirrel", id: 1669664068
mas "TabifyIndents", id: 1179234554
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
mas "Tunacan", id: 980577198
mas "uBlacklist for Safari", id: 1547912640
mas "Userscripts", id: 1463298887
mas "Velja", id: 1607635845
mas "Vimari", id: 1480933944
mas "VisBug", id: 1538509686
mas "WhatsApp", id: 310633997
mas "WhisperAX", id: 0
mas "Xcode", id: 497799835
vscode "aaron-bond.better-comments"
vscode "akamud.vscode-theme-onedark"
vscode "alefragnani.bookmarks"
vscode "alexcvzz.vscode-sqlite"
vscode "anseki.vscode-color"
vscode "antfu.browse-lite"
vscode "antfu.file-nesting"
vscode "antfu.iconify"
vscode "antfu.open-in-github-button"
vscode "antfu.pnpm-catalog-lens"
vscode "antfu.slidev"
vscode "antfu.smart-clicks"
vscode "antfu.unocss"
vscode "antonholmberg.remove-bg"
vscode "arjun.swagger-viewer"
vscode "astro-build.astro-vscode"
vscode "asvetliakov.vscode-neovim"
vscode "azurite.azurite"
vscode "be5invis.toml"
vscode "be5invis.vscode-custom-css"
vscode "bencoleman.armview"
vscode "bierner.github-markdown-preview"
vscode "bierner.markdown-checkbox"
vscode "bierner.markdown-emoji"
vscode "bierner.markdown-footnotes"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bierner.markdown-yaml-preamble"
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "cab404.vscode-direnv"
vscode "chakrounanas.turbo-console-log"
vscode "christian-kohler.path-intellisense"
vscode "chrmarti.regex"
vscode "cnshenj.vscode-task-manager"
vscode "codezombiech.gitignore"
vscode "coolbear.systemd-unit-file"
vscode "crewsycrews.bundlephobia-support"
vscode "cschlosser.doxdocgen"
vscode "cstrap.python-snippets"
vscode "davidbroetje.algorithm-mnemonics-vscode"
vscode "dbaeumer.vscode-eslint"
vscode "deerawan.vscode-dash"
vscode "deerawan.vscode-faker"
vscode "denoland.vscode-deno"
vscode "docker.docker"
vscode "dominicvonk.auto-toggle-sidebar"
vscode "donjayamanne.githistory"
vscode "dotjoshjohnson.xml"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "extr0py.vscode-relative-line-numbers"
vscode "fabiospampinato.vscode-open-in-github"
vscode "fivethree.vscode-svelte-snippets"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "formulahendry.github-actions"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.remotehub"
vscode "github.vscode-codeql"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "grapecity.gc-excelviewer"
vscode "gruntfuggly.todo-tree"
vscode "helgardrichard.helium-icon-theme"
vscode "hnw.vscode-auto-open-markdown-preview"
vscode "humao.rest-client"
vscode "hyesun.py-paste-indent"
vscode "ibm.output-colorizer"
vscode "icrawl.discord-vscode"
vscode "ics.japanese-proofreading"
vscode "jakob101.relativepath"
vscode "james-yu.latex-workshop"
vscode "janisdd.vscode-edit-csv"
vscode "jeff-hykin.better-cpp-syntax"
vscode "jock.svg"
vscode "jonathanharty.gruvbox-material-icon-theme"
vscode "jrebocho.vscode-random"
vscode "julianiaquinandi.nvim-ui-modifier"
vscode "kawamurakazushi.vscode-filer"
vscode "lokalise.i18n-ally"
vscode "lucax88x.codeacejumper"
vscode "marp-team.marp-vscode"
vscode "mechatroner.rainbow-csv"
vscode "metaseed.metajump"
vscode "mhutchie.git-graph"
vscode "mosapride.zenkaku"
vscode "mrmlnc.vscode-duplicate"
vscode "ms-azure-devops.azure-pipelines"
vscode "ms-azure-load-testing.microsoft-testing"
vscode "ms-azuretools.azure-dev"
vscode "ms-azuretools.vscode-azure-github-copilot"
vscode "ms-azuretools.vscode-azureappservice"
vscode "ms-azuretools.vscode-azurecontainerapps"
vscode "ms-azuretools.vscode-azurefunctions"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestaticwebapps"
vscode "ms-azuretools.vscode-azurestorage"
vscode "ms-azuretools.vscode-azurevirtualmachines"
vscode "ms-azuretools.vscode-bicep"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-cosmosdb"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-dotnettools.vscodeintellicode-csharp"
vscode "ms-edgedevtools.vscode-edge-devtools"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.azurecli"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.remote-server"
vscode "ms-vscode.theme-materialkit"
vscode "ms-vscode.vscode-node-azure-pack"
vscode "ms-vscode.vscode-speech"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-windows-ai-studio.windows-ai-studio"
vscode "msazurermtools.azurerm-vscode-tools"
vscode "mtxr.sqltools"
vscode "mtxr.sqltools-driver-mssql"
vscode "mtxr.sqltools-driver-mysql"
vscode "mtxr.sqltools-driver-pg"
vscode "mtxr.sqltools-driver-sqlite"
vscode "nickdemayo.vscode-json-editor"
vscode "nrwl.angular-console"
vscode "oderwat.indent-rainbow"
vscode "oven.bun-vscode"
vscode "patricklee.vsnotes"
vscode "peakchen90.open-html-in-browser"
vscode "pizzacat83.codic"
vscode "pomber.git-file-history"
vscode "postman.postman-for-vscode"
vscode "pranthiks.sendmail"
vscode "praveencrony.total-lines"
vscode "qufiwefefwoyn.kanagawa"
vscode "rcore.rcore-unused-css-classes"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.create-file-folder"
vscode "ritwickdey.liveserver"
vscode "rogalmic.bash-debug"
vscode "rubymaniac.vscode-direnv"
vscode "rust-lang.rust-analyzer"
vscode "ryanolsonx.snippet-creator"
vscode "sgryjp.japanese-word-handler"
vscode "shardulm94.trailing-spaces"
vscode "shopify.vscode-shadowenv"
vscode "simonsiefke.svg-preview"
vscode "skyapps.fish-vscode"
vscode "statelyai.stately-vscode"
vscode "stordahl.sveltekit-snippets"
vscode "styled-components.vscode-styled-components"
vscode "sumneko.lua"
vscode "svelte.svelte-vscode"
vscode "tabnine.tabnine-vscode"
vscode "tamasfe.even-better-toml"
vscode "tcwalther.cython"
vscode "teamsdevapp.vscode-ai-foundry"
vscode "tekumara.typos-vscode"
vscode "tomoki1207.pdf"
vscode "tshino.dynamic-macro"
vscode "tshino.kb-macro"
vscode "tushortz.python-extended-snippets"
vscode "twxs.cmake"
vscode "ulwlu.elly"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vitest.explorer"
vscode "vscode-icons-team.vscode-icons"
vscode "vsls-contrib.gistfs"
vscode "vue.volar"
vscode "wakatime.vscode-wakatime"
vscode "wayou.vscode-todo-highlight"
vscode "webfreak.debug"
vscode "wicked-labs.sequoia"
vscode "wix.vscode-import-cost"
vscode "wmaurer.change-case"
vscode "wraith13.bracket-lens"
vscode "wraith13.file-path-bar"
vscode "yclepticstudios.unity-snippets"
vscode "yoavbls.pretty-ts-errors"
vscode "yummygum.city-lights-theme"
vscode "yzane.markdown-pdf"
vscode "zhuangtongfa.material-theme"
vscode "ziglang.vscode-zig"
vscode "zxh404.vscode-proto3"
