tap "a-know/tap"
tap "adoptopenjdk/openjdk"
tap "agrinman/tap"
tap "aquaproj/aqua"
tap "aquasecurity/trivy"
tap "argon/mas"
tap "arrow2nd/tap"
tap "aws/tap"
tap "azure/functions"
tap "b4b4r07/tap"
tap "bazelbuild/tap"
tap "cantino/mcfly", "https://github.com/cantino/mcfly"
tap "charmbracelet/tap"
tap "cloudflare/cloudflare"
tap "danielbayley/alfred"
tap "dorukgezici/cask"
tap "dwarvesf/tap"
tap "eugenmayer/dockersync"
tap "facebook/fb"
tap "felixkratz/formulae"
tap "fsouza/prettierd"
tap "gcenx/wine"
tap "github/gh"
tap "go-delve/delve"
tap "goodwithtech/r"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "itchyny/tap"
tap "jakehilborn/jakehilborn"
tap "jesseduffield/lazygit"
tap "koekeishiya/formulae"
tap "kryptco/tap"
tap "microsoft/git"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "planetscale/tap"
tap "possatti/possatti"
tap "qmk/qmk"
tap "rcmdnk/file"
tap "rhysd/actionlint", "https://github.com/rhysd/actionlint"
tap "ryoppippi/neovim-nightly"
tap "sanemat/font"
tap "skanehira/docui"
tap "supabase/tap"
tap "thought-machine/please"
tap "tinygo-org/tools"
tap "uzimaru0000/tap"
tap "wez/wezterm"
tap "yt-dlp/taps"
tap "yudai/gotty"
brew "libpng"
brew "little-cms2"
brew "aom"
brew "apr-util"
brew "gettext"
brew "libssh2"
brew "aria2"
brew "gcc"
brew "open-mpi"
brew "arpack"
brew "atool"
brew "autoconf"
brew "automake"
brew "bandwhich"
brew "bash"
brew "bash-completion"
brew "freetype"
brew "fontconfig"
brew "glib"
brew "libffi"
brew "pkg-config"
brew "python@3.9"
brew "cairo"
brew "graphite2"
brew "harfbuzz"
brew "openjdk@11"
brew "bazel"
brew "bdw-gc"
brew "libunistring"
brew "libidn2"
brew "libuv"
brew "bind"
brew "bison"
brew "bit-git"
brew "bluetoothconnector"
brew "boost"
brew "ccache"
brew "ccls"
brew "metis"
brew "suite-sparse"
brew "clang-format"
brew "cloc"
brew "cmake"
brew "cmatrix"
brew "libyaml"
brew "cocoapods"
brew "coreutils"
brew "cowsay"
brew "ctop"
brew "curl"
brew "dlib"
brew "dnsmasq"
brew "docker-compose"
brew "folly"
brew "efm-langserver"
brew "envchain"
brew "openjpeg"
brew "ghostscript"
brew "epstool"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "libogg"
brew "flac"
brew "frei0r"
brew "fribidi"
brew "libtasn1"
brew "unbound"
brew "gnutls"
brew "lame"
brew "leptonica"
brew "libass"
brew "libbluray"
brew "libsamplerate"
brew "libvorbis"
brew "mpg123"
brew "libsndfile"
brew "libsoxr"
brew "libvidstab"
brew "libvpx"
brew "pango"
brew "sdl2"
brew "tesseract"
brew "zeromq"
brew "ffmpeg"
brew "ffmpeg@4"
brew "fftw"
brew "fig2dev"
brew "figlet"
brew "fish"
brew "fltk"
brew "fortune"
brew "libtool"
brew "fswatch"
brew "fzy"
brew "gawk"
brew "libavif"
brew "gd"
brew "gdk-pixbuf"
brew "ghq"
brew "gibo"
brew "git"
brew "libgit2"
brew "git-interactive-rebase-tool"
brew "git-lfs"
brew "gl2ps"
brew "glfw"
brew "glow"
brew "glpk"
brew "gnu-sed"
brew "libcerf"
brew "qt@5"
brew "gnuplot"
brew "gobject-introspection"
brew "gperftools"
brew "gping"
brew "gts"
brew "librsvg"
brew "graphviz"
brew "grex"
brew "hadolint"
brew "hdf5"
brew "hexedit"
brew "hexyl"
brew "htop"
brew "httpstat"
brew "icoutils"
brew "ilmbase"
brew "libde265"
brew "shared-mime-info"
brew "libheif"
brew "libomp", link: true
brew "imagemagick"
brew "ios-deploy"
brew "jc"
brew "jemalloc"
brew "jid"
brew "lapack"
brew "openjdk"
brew "leiningen"
brew "libcroco"
brew "libepoxy"
brew "libusb"
brew "libusbmuxd"
brew "libimobiledevice"
brew "libslirp"
brew "libspiro"
brew "libssh"
brew "libtermkey"
brew "libuninameslist"
brew "libzip"
brew "llvm"
brew "llvm@13"
brew "lolcat"
brew "lynx"
brew "mackup"
brew "make"
brew "mas"
brew "massren"
brew "mdcat"
brew "media-info"
brew "mercurial"
brew "protobuf"
brew "mosh"
brew "msgpack"
brew "zlib"
brew "mysql-client"
brew "neovim"
brew "ninja"
brew "nmap"
brew "node@16"
brew "nspr"
brew "nss"
brew "numpy"
brew "plotutils"
brew "portaudio"
brew "pstoedit"
brew "pyqt@5"
brew "qhull"
brew "qrupdate"
brew "qscintilla2"
brew "sundials"
brew "octave"
brew "vtk"
brew "opencv"
brew "opusfile"
brew "parallel"
brew "pastel"
brew "php"
brew "ponysay"
brew "poppler"
brew "procs"
brew "pv"
brew "pwgen"
brew "qt"
brew "pyqt"
brew "python-tk@3.9"
brew "python@3.8"
brew "qemu"
brew "ranger"
brew "rclone"
brew "reattach-to-user-namespace"
brew "rlwrap"
brew "rsync"
brew "rust-analyzer"
brew "screenfetch"
brew "screenresolution"
brew "silicon"
brew "sip"
brew "sl"
brew "smartmontools"
brew "sox"
brew "sphinx-doc"
brew "stylua"
brew "swift-format"
brew "swiftlint"
brew "switchaudio-osx"
brew "t-rec"
brew "ta-lib"
brew "telnet"
brew "terminal-notifier"
brew "tldr"
brew "topgrade"
brew "translate-shell"
brew "tree"
brew "ttyd"
brew "ttyrec"
brew "unison"
brew "utf8proc"
brew "veclibfort"
brew "w3m"
brew "wallpaper"
brew "watch"
brew "watchexec"
brew "watchman"
brew "wget"
brew "whalebrew"
brew "xcodegen"
brew "xcv"
brew "youtube-dl"
brew "zsh-completions"
brew "a-know/tap/pi"
brew "aquaproj/aqua/aqua"
brew "aquasecurity/trivy/trivy"
brew "arrow2nd/tap/nekome"
brew "cantino/mcfly/mcfly"
brew "charmbracelet/tap/vhs"
brew "cloudflare/cloudflare/cloudflared"
brew "eugenmayer/dockersync/unox"
brew "goodwithtech/r/dockle"
brew "itchyny/tap/mmv"
brew "jakehilborn/jakehilborn/displayplacer"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "possatti/possatti/pokemonsay"
brew "supabase/tap/supabase"
brew "yt-dlp/taps/yt-dlp"
cask "aerial"
cask "alfred"
cask "alt-tab"
cask "appcleaner"
cask "arduino"
cask "audacity"
cask "balenaetcher"
cask "basictex"
cask "blackhole-16ch"
cask "blackhole-2ch"
cask "blender"
cask "bleunlock"
cask "blu-ray-player-pro"
cask "bluesnooze"
cask "cheatsheet"
cask "cloudflare-warp"
cask "coconutbattery"
cask "corretto8"
cask "cyberduck"
cask "dash"
cask "db-browser-for-sqlite"
cask "deepl"
cask "discord"
cask "finicky"
cask "git-credential-manager-core"
cask "gitify"
cask "google-chrome"
cask "google-drive"
cask "gyazo"
cask "haptickey"
cask "hot"
cask "imageoptim"
cask "jetbrains-toolbox"
cask "jettison"
cask "jupyter-notebook-viewer"
cask "karabiner-elements"
cask "keycastr"
cask "licecap"
cask "lulu"
cask "microsoft-auto-update"
cask "microsoft-azure-storage-explorer"
cask "microsoft-edge"
cask "min"
cask "miniforge"
cask "monitorcontrol"
cask "ngrok"
cask "noisebuddy"
cask "notunes"
cask "numi"
cask "obs"
cask "obsidian"
cask "orbstack"
cask "processing"
cask "qlvideo"
cask "quitter"
cask "raspberry-pi-imager"
cask "rectangle"
cask "rstudio"
cask "sdformatter"
cask "sequel-pro-nightly"
cask "shortcat"
cask "shottr"
cask "signal"
cask "skype"
cask "ssh-tunnel-manager"
cask "suspicious-package"
cask "syncthing"
cask "tor-browser"
cask "touch-bar-simulator"
cask "transmission-nightly"
cask "tunnelblick"
cask "tweeten"
cask "vimmotion"
cask "visual-studio-code"
cask "vlc"
cask "wezterm"
cask "window-switch"
cask "xquartz"
cask "zerotier-one"
cask "zoom"
mas "Accelerate", id: 1459809092
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Auto HD FPS for YouTube", id: 1546729687
mas "Be Focused", id: 973134470
mas "BlockComment", id: 1246672247
mas "Clean", id: 418412301
mas "CotEditor", id: 1024640650
mas "DevCleaner", id: 1388020431
mas "Disk Speed Test", id: 425264550
mas "Document Generator", id: 1437883178
mas "Downlink", id: 1454269192
mas "Download Shuttle", id: 847809913
mas "DuckDuckGo Privacy for Safari", id: 1482920575
mas "Gemini 2", id: 1090488118
mas "Gifski", id: 1351639930
mas "GIPHY CAPTURE", id: 668208984
mas "Grammarly for Safari", id: 1462114288
mas "Hex Fiend", id: 1342896380
mas "iHosts", id: 1102004240
mas "iText Express", id: 416550249
mas "Keepa - Price Tracker", id: 1533805339
mas "Keynote", id: 409183694
mas "Keyword Search", id: 1558453954
mas "LadioCast", id: 411213048
mas "LanguageTranslator", id: 1218781096
mas "LINE", id: 539883307
mas "Mathpix Snipping Tool", id: 1349670778
mas "Mendeley Web Importer", id: 1577516695
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "NamingTranslator", id: 1218784832
mas "OctoLinker", id: 1549308269
mas "Pages", id: 409201541
mas "PicGIF Lite", id: 844918735
mas "PiPifier", id: 1160374471
mas "Refined GitHub", id: 1519867270
mas "Screegle", id: 1591051659
mas "Seashore", id: 1448648921
mas "Sequel Ace", id: 1518036000
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Speedtest", id: 1153157709
mas "TabifyIndents", id: 1179234554
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
mas "Tunacan", id: 980577198
mas "uBlacklist for Safari", id: 1547912640
mas "Vimari", id: 1480933944
mas "VisBug", id: 1538509686
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
mas "XnConvert", id: 436203431
