[tools]
zig = "master"
rust = "latest"
rust-analyzer = "latest"
"cargo:cargo-watch" = "latest"
neovim = "nightly"
"cargo:cargo-expand" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-outdated" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-bisect-rustc" = "latest"

[settings]
experimental = true
