gui:
  nerdFontsVersion: "3"
git:
  allBranchesLogCmd: "git log --pretty=format:\"%Cgreen%h %Creset%cd %Cblue[%cn] %Creset%s%C(yellow)%d%C(reset)\" --graph --date=relative --decorate --all"
  branchLogCmd: "git log --pretty=format:\"%Cgreen%h %Creset%cd %Cblue[%cn] %Creset%s%C(yellow)%d%C(reset)\" --graph --date=relative --decorate {{branchName}} --"

  paging:
    colorArg: always
    pager: delta --color-only --dark --paging=never

