# lazy2nix — serve lazy.nvim plugins from the Nix store.
#
# Consumes the two files generated by `nix run .#lazy2nix` (generate.ts):
# nixpkgs-packaged plugins come straight from vimPlugins, the rest are
# built from GitHub sources pinned at the commit lazy-lock.json recorded
# when they were last git-managed. The resulting list feeds one linkFarm
# whose entry names match lazy.nvim's plugin directory names, resolved at
# runtime through `dev.path` ($LAZY_NIX_PLUGINS).
{ pkgs, lib }:
let
  fromNixpkgs = lib.mapAttrsToList (name: attr: {
    inherit name;
    path = pkgs.vimPlugins.${attr};
  }) (import ./nixpkgs-plugins.nix);

  buildPinned = name: pin: {
    inherit name;
    path = pkgs.vimUtils.buildVimPlugin {
      pname = name;
      version = builtins.substring 0 8 pin.rev;
      src = pkgs.fetchFromGitHub {
        inherit (pin)
          owner
          repo
          rev
          hash
          ;
      };
      # the require check needs every optional dependency on the path;
      # these sources are known-good at the locked commit
      doCheck = false;
    };
  };
  pinned = lib.mapAttrsToList buildPinned (
    builtins.fromJSON (builtins.readFile ./pinned-plugins.json)
  );
in
{
  plugins = fromNixpkgs ++ pinned;
}
