# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = {
    "@actions/expressions-0.3.20" = {
      name = "_at_actions_slash_expressions";
      packageName = "@actions/expressions";
      version = "0.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/expressions/-/expressions-0.3.20.tgz";
        sha512 = "AZ8lfVjBXD2K6jzkLj2CsLx9ppI9CzqnfdH4J3ZSp1pRWHL3bURpqyTs8zg2tCJb7zoR8Gsw3DTxPKfvGwQKrA==";
      };
    };
    "@actions/languageserver-0.3.20" = {
      name = "_at_actions_slash_languageserver";
      packageName = "@actions/languageserver";
      version = "0.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/languageserver/-/languageserver-0.3.20.tgz";
        sha512 = "UI1Qi/SJzrMpqhwd6AfyK9rMYy71ueIFtHjLmNxEqaDMRUj06/LUaE9F2mWM29xOD3CVs1gZrGpQtuIY3QGxtg==";
      };
    };
    "@actions/languageservice-0.3.20" = {
      name = "_at_actions_slash_languageservice";
      packageName = "@actions/languageservice";
      version = "0.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/languageservice/-/languageservice-0.3.20.tgz";
        sha512 = "s8DiUNKew9+IdRVqu2jxVmpPU7kIegQ9vSfhXxBbGkFLqkJANhg+M6tt3oEwgTtaUH1r44rccfrocATZZNaH5A==";
      };
    };
    "@actions/workflow-parser-0.3.20" = {
      name = "_at_actions_slash_workflow-parser";
      packageName = "@actions/workflow-parser";
      version = "0.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/workflow-parser/-/workflow-parser-0.3.20.tgz";
        sha512 = "qhIzkiTiyiYX0CaIR+SS5Z0g7BMqS6VIC0t4GZH8lVGbK6Yw+0TpSX8iTFySfZMMoVpSCFy6uBxekskvBpkqEQ==";
      };
    };
    "@jridgewell/gen-mapping-0.3.13" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz";
        sha512 = "2kkt/7niJ6MgEPxF0bYdQ6etZaA+fQvDcLKckhy1yIQOzaoKjBBjSj63/aLVjYE3qhRt5dvM+uUyfCg6UKCBbA==";
      };
    };
    "@jridgewell/remapping-2.3.5" = {
      name = "_at_jridgewell_slash_remapping";
      packageName = "@jridgewell/remapping";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/remapping/-/remapping-2.3.5.tgz";
        sha512 = "LI9u/+laYG4Ds1TDKSJW2YPrIlcVYOwi2fUC6xB43lueCjgxV4lffOCZCtYFiH6TNOX+tQKXx97T4IKHbhyHEQ==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.5" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
        sha512 = "cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
      };
    };
    "@jridgewell/trace-mapping-0.3.31" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz";
        sha512 = "zzNR+SdQSDJzc8joaeP8QQoCQr8NuYx2dIIytl1QeBEZHJ9uW6hebsrYgbz8hJwUQao3TWCMtmfV8Nu1twOLAw==";
      };
    };
    "@octokit/auth-token-3.0.4" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-3.0.4.tgz";
        sha512 = "TWFX7cZF2LXoCvdmJWY7XVPi74aSY0+FfBZNSXEXFkMpjcqsQwDSYVv5FhRFaI0V1ECnwbz4j59T/G+rXNWaIQ==";
      };
    };
    "@octokit/auth-token-5.1.2" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-5.1.2.tgz";
        sha512 = "JcQDsBdg49Yky2w2ld20IHAlwr8d/d8N6NiOXbtuoPCqzbsiJgF633mVUw3x4mo0H5ypataQIX7SFu3yy44Mpw==";
      };
    };
    "@octokit/core-4.2.4" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-4.2.4.tgz";
        sha512 = "rYKilwgzQ7/imScn3M9/pFfUf4I1AZEH3KhyJmtPdE2zfaXAn2mFfUy4FbKewzc2We5y/LlKLj36fWJLKC2SIQ==";
      };
    };
    "@octokit/core-6.1.6" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "6.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-6.1.6.tgz";
        sha512 = "kIU8SLQkYWGp3pVKiYzA5OSaNF5EE03P/R8zEmmrG6XwOg5oBjXyQVVIauQ0dgau4zYhpZEhJrvIYt6oM+zZZA==";
      };
    };
    "@octokit/endpoint-10.1.4" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "10.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-10.1.4.tgz";
        sha512 = "OlYOlZIsfEVZm5HCSR8aSg02T2lbUWOsCQoPKfTXJwDzcHQBrVBGdGXb89dv2Kw2ToZaRtudp8O3ZIYoaOjKlA==";
      };
    };
    "@octokit/endpoint-7.0.6" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-7.0.6.tgz";
        sha512 = "5L4fseVRUsDFGR00tMWD/Trdeeihn999rTMGRMC1G/Ldi1uWlWJzI98H4Iak5DB/RVvQuyMYKqSK/R6mbSOQyg==";
      };
    };
    "@octokit/graphql-5.0.6" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "5.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-5.0.6.tgz";
        sha512 = "Fxyxdy/JH0MnIB5h+UQ3yCoh1FG4kWXfFKkpWqjZHw/p+Kc8Y44Hu/kCgNBT6nU1shNumEchmW/sUO1JuQnPcw==";
      };
    };
    "@octokit/graphql-8.2.2" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "8.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-8.2.2.tgz";
        sha512 = "Yi8hcoqsrXGdt0yObxbebHXFOiUA+2v3n53epuOg1QUgOB6c4XzvisBNVXJSl8RYA5KrDuSL2yq9Qmqe5N0ryA==";
      };
    };
    "@octokit/openapi-types-18.1.1" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "18.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-18.1.1.tgz";
        sha512 = "VRaeH8nCDtF5aXWnjPuEMIYf1itK/s3JYyJcWFJT8X9pSNnBtriDf7wlEWsGuhPLl4QIH4xM8fqTXDwJ3Mu6sw==";
      };
    };
    "@octokit/openapi-types-24.2.0" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "24.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-24.2.0.tgz";
        sha512 = "9sIH3nSUttelJSXUrmGzl7QUBFul0/mB8HRYl3fOlgHbIWG+WnYDXU3v/2zMtAvuzZ/ed00Ei6on975FhBfzrg==";
      };
    };
    "@octokit/openapi-types-25.1.0" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "25.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-25.1.0.tgz";
        sha512 = "idsIggNXUKkk0+BExUn1dQ92sfysJrje03Q0bv0e+KPLrvyqZF8MnBpFz8UNfYDwB3Ie7Z0TByjWfzxt7vseaA==";
      };
    };
    "@octokit/plugin-paginate-rest-11.6.0" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "11.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-11.6.0.tgz";
        sha512 = "n5KPteiF7pWKgBIBJSk8qzoZWcUkza2O6A0za97pMGVrGfPdltxrfmfF5GucHYvHGZD8BdaZmmHGz5cX/3gdpw==";
      };
    };
    "@octokit/plugin-paginate-rest-6.1.2" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "6.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-6.1.2.tgz";
        sha512 = "qhrmtQeHU/IivxucOV1bbI/xZyC/iOBhclokv7Sut5vnejAIAEXVcGQeRpQlU39E0WwK9lNvJHphHri/DB6lbQ==";
      };
    };
    "@octokit/plugin-request-log-1.0.4" = {
      name = "_at_octokit_slash_plugin-request-log";
      packageName = "@octokit/plugin-request-log";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-request-log/-/plugin-request-log-1.0.4.tgz";
        sha512 = "mLUsMkgP7K/cnFEw07kWqXGF5LKrOkD+lhCrKvPHXWDywAwuDUeDwWBpc69XK3pNX0uKiVt8g5z96PJ6z9xCFA==";
      };
    };
    "@octokit/plugin-request-log-5.3.1" = {
      name = "_at_octokit_slash_plugin-request-log";
      packageName = "@octokit/plugin-request-log";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-request-log/-/plugin-request-log-5.3.1.tgz";
        sha512 = "n/lNeCtq+9ofhC15xzmJCNKP2BWTv8Ih2TTy+jatNCCq/gQP/V7rK3fjIfuz0pDWDALO/o/4QY4hyOF6TQQFUw==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-13.5.0" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "13.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-13.5.0.tgz";
        sha512 = "9Pas60Iv9ejO3WlAX3maE1+38c5nqbJXV5GrncEfkndIpZrJ/WPMRd2xYDcPPEt5yzpxcjw9fWNoPhsSGzqKqw==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-7.2.3" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-7.2.3.tgz";
        sha512 = "I5Gml6kTAkzVlN7KCtjOM+Ruwe/rQppp0QU372K1GP7kNOYEKe8Xn5BW4sE62JAHdwpq95OQK/qGNyKQMUzVgA==";
      };
    };
    "@octokit/request-6.2.8" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "6.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-6.2.8.tgz";
        sha512 = "ow4+pkVQ+6XVVsekSYBzJC0VTVvh/FCTUUgTsboGq+DTeWdyIFV8WSCdo0RIxk6wSkBTHqIK1mYuY7nOBXOchw==";
      };
    };
    "@octokit/request-9.2.4" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-9.2.4.tgz";
        sha512 = "q8ybdytBmxa6KogWlNa818r0k1wlqzNC+yNkcQDECHvQo8Vmstrg18JwqJHdJdUiHD2sjlwBgSm9kHkOKe2iyA==";
      };
    };
    "@octokit/request-error-3.0.3" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-3.0.3.tgz";
        sha512 = "crqw3V5Iy2uOU5Np+8M/YexTlT8zxCfI+qu+LxUB7SZpje4Qmx3mub5DfEKSO8Ylyk0aogi6TYdf6kxzh2BguQ==";
      };
    };
    "@octokit/request-error-6.1.8" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "6.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-6.1.8.tgz";
        sha512 = "WEi/R0Jmq+IJKydWlKDmryPcmdYSVjL3ekaiEL1L9eo1sUnqMJ+grqmC9cjk7CA7+b2/T397tO5d8YLOH3qYpQ==";
      };
    };
    "@octokit/rest-19.0.13" = {
      name = "_at_octokit_slash_rest";
      packageName = "@octokit/rest";
      version = "19.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/rest/-/rest-19.0.13.tgz";
        sha512 = "/EzVox5V9gYGdbAI+ovYj3nXQT1TtTHRT+0eZPcuC05UFSWO3mdO9UY1C0i2eLF9Un1ONJkAk+IEtYGAC+TahA==";
      };
    };
    "@octokit/rest-21.1.1" = {
      name = "_at_octokit_slash_rest";
      packageName = "@octokit/rest";
      version = "21.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/rest/-/rest-21.1.1.tgz";
        sha512 = "sTQV7va0IUVZcntzy1q3QqPm/r8rWtDCqpRAmb8eXXnKkjoQEtFe3Nt5GTVsHft+R6jJoHeSiVLcgcvhtue/rg==";
      };
    };
    "@octokit/tsconfig-1.0.2" = {
      name = "_at_octokit_slash_tsconfig";
      packageName = "@octokit/tsconfig";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/tsconfig/-/tsconfig-1.0.2.tgz";
        sha512 = "I0vDR0rdtP8p2lGMzvsJzbhdOWy405HcGovrspJ8RRibHnyRgggUSNO5AIox5LmqiwmatHKYsvj6VGFHkqS7lA==";
      };
    };
    "@octokit/types-10.0.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-10.0.0.tgz";
        sha512 = "Vm8IddVmhCgU1fxC1eyinpwqzXPEYu0NrYzD3YZjlGjyftdLBTeqNblRC0jmJmgxbJIsQlyogVeGnrNaaMVzIg==";
      };
    };
    "@octokit/types-13.10.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "13.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-13.10.0.tgz";
        sha512 = "ifLaO34EbbPj0Xgro4G5lP5asESjwHracYJvVaPIyXMuiuXLlhic3S47cBdTb+jfODkTE5YtGCLt3Ay3+J97sA==";
      };
    };
    "@octokit/types-14.1.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-14.1.0.tgz";
        sha512 = "1y6DgTy8Jomcpu33N+p5w58l6xyt55Ar2I91RPiIA0xCJBXyUAhXCcmZaDWSANiha7R9a6qJJ2CRomGPZ6f46g==";
      };
    };
    "@octokit/types-9.3.2" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "9.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-9.3.2.tgz";
        sha512 = "D4iHGTdAnEEVsB8fl95m1hiz7D5YiRdQ9b/OEb3BYRVwbLsGHcRVPz+u+BgRLNk0Q0/4iZCBqDN96j2XNxfXrA==";
      };
    };
    "@quansync/fs-0.1.5" = {
      name = "_at_quansync_slash_fs";
      packageName = "@quansync/fs";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@quansync/fs/-/fs-0.1.5.tgz";
        sha512 = "lNS9hL2aS2NZgNW7BBj+6EBl4rOf8l+tQ0eRY6JWCI8jI2kc53gSoqbjojU0OnAWhzoXiOjFyGsHcDGePB3lhA==";
      };
    };
    "@sveltejs/acorn-typescript-1.0.7" = {
      name = "_at_sveltejs_slash_acorn-typescript";
      packageName = "@sveltejs/acorn-typescript";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/acorn-typescript/-/acorn-typescript-1.0.7.tgz";
        sha512 = "znp1A/Y1Jj4l/Zy7PX5DZKBE0ZNY+5QBngiE21NJkfSTyzzC5iKNWOtwFXKtIrn7MXEFBck4jD95iBNkGjK92Q==";
      };
    };
    "@types/estree-1.0.8" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz";
        sha512 = "dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
      };
    };
    "@unocss/autocomplete-66.5.9" = {
      name = "_at_unocss_slash_autocomplete";
      packageName = "@unocss/autocomplete";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/autocomplete/-/autocomplete-66.5.9.tgz";
        sha512 = "CyWob9D4nrkWWctaIXFt62kHGF7C5u1LK0NlvzEr/6qdpA+YOTlFRYCLI3E8+hJU/xOYxX12hNE9j2dtPOj7Mw==";
      };
    };
    "@unocss/config-66.5.9" = {
      name = "_at_unocss_slash_config";
      packageName = "@unocss/config";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/config/-/config-66.5.9.tgz";
        sha512 = "M8O0Z+6iCXuQOz/quaKueSb2cmN7cP9JGWdAH2E+qFD8txljaY88tNL4OwFZtO9GjhT2f/pEsLoEOAtAo1xT6g==";
      };
    };
    "@unocss/core-66.5.9" = {
      name = "_at_unocss_slash_core";
      packageName = "@unocss/core";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/core/-/core-66.5.9.tgz";
        sha512 = "0ch1dN1AJFX+QCxaQR6WLfWqr8PHt7U/wqSTm5vdLXTsm96R7ggCGMs360TiDMimDUvXak6gka+y/6wdQBf8/A==";
      };
    };
    "@unocss/extractor-arbitrary-variants-66.5.9" = {
      name = "_at_unocss_slash_extractor-arbitrary-variants";
      packageName = "@unocss/extractor-arbitrary-variants";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/extractor-arbitrary-variants/-/extractor-arbitrary-variants-66.5.9.tgz";
        sha512 = "b+D6HbtN4hpGcThdJ8IVPl3xXdNN//Rw+WhyIuRdjwCPMsOfLnEqehPm1f5Rcc+xfFwxYJwC35SZnoBSrRMULg==";
      };
    };
    "@unocss/preset-mini-66.5.9" = {
      name = "_at_unocss_slash_preset-mini";
      packageName = "@unocss/preset-mini";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-mini/-/preset-mini-66.5.9.tgz";
        sha512 = "5SxMTT8kRi+SFNfTKUvFBA4E/4H5BwD5RPNeIbrNlHdeltK8rwCMpXWu5AihNR1kKt5JBBqe/8m0UdoZzAK0+A==";
      };
    };
    "@unocss/preset-wind3-66.5.9" = {
      name = "_at_unocss_slash_preset-wind3";
      packageName = "@unocss/preset-wind3";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-wind3/-/preset-wind3-66.5.9.tgz";
        sha512 = "eT23SDqksr6LVzkJLDkGGNIBpRevMHIrretM8VNI7PECJEcpFwX9sgWn3yxAsqy5+0hJXuvFBc9BRUN6sHl5hQ==";
      };
    };
    "@unocss/rule-utils-66.5.9" = {
      name = "_at_unocss_slash_rule-utils";
      packageName = "@unocss/rule-utils";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/rule-utils/-/rule-utils-66.5.9.tgz";
        sha512 = "ZdtWqbOaNQLf6NFhcEkvaBf0fjm5GZP5NV/plmQEqK6ehe1TTpaqOtO0LBFD2BUy72oXlcsFnvdgWt/CpL6FLg==";
      };
    };
    "acorn-8.15.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
        sha512 = "NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      };
    };
    "aria-query-5.3.2" = {
      name = "aria-query";
      packageName = "aria-query";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-query/-/aria-query-5.3.2.tgz";
        sha512 = "COROpnaoap1E2F000S62r6A60uHZnmlvomhfyT2DlTcrY1OrBKn2UhH7qn5wTC9zMvD0AY7csdPSNwKP+7WiQw==";
      };
    };
    "axobject-query-4.1.0" = {
      name = "axobject-query";
      packageName = "axobject-query";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axobject-query/-/axobject-query-4.1.0.tgz";
        sha512 = "qIj0G9wZbMGNLjLmg1PT6v2mE9AH2zlnADJD/2tC6E00hgmhUOfEB6greHPAfLRSufHqROIUTkw6E+M3lH0PTQ==";
      };
    };
    "before-after-hook-2.2.3" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-2.2.3.tgz";
        sha512 = "NzUnlZexiaH/46WDhANlyR2bXRopNg4F/zuSA3OpZnllCUgRaOF2znDioDWrmbNVsuZk6l9pMquQB38cfBZwkQ==";
      };
    };
    "before-after-hook-3.0.2" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-3.0.2.tgz";
        sha512 = "Nik3Sc0ncrMK4UUdXQmAnRtzmNQTAAXmXIopizwZ1W1t8QmfJj+zL4OA2I7XPTPW5z5TDqv4hRo/JzouDJnX3A==";
      };
    };
    "clsx-2.1.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-2.1.1.tgz";
        sha512 = "eYm0QWBtUrBWZWG0d386OGAw16Z995PiOVo2B7bjWSbHedGl5e0ZWaq65kOGgUSNesEIDkB9ISbTg/JK9dhCZA==";
      };
    };
    "color-name-2.1.0" = {
      name = "color-name";
      packageName = "color-name";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-2.1.0.tgz";
        sha512 = "1bPaDNFm0axzE4MEAzKPuqKWeRaT43U/hyxKPBdqTfmPF+d6n7FSoTFxLVULUJOmiLp01KjhIPPH+HrXZJN4Rg==";
      };
    };
    "color-parse-2.0.2" = {
      name = "color-parse";
      packageName = "color-parse";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-parse/-/color-parse-2.0.2.tgz";
        sha512 = "eCtOz5w5ttWIUcaKLiktF+DxZO1R9KLNY/xhbV6CkhM7sR3GhVghmt6X6yOnzeaM24po+Z9/S1apbXMwA3Iepw==";
      };
    };
    "color-rgba-3.0.0" = {
      name = "color-rgba";
      packageName = "color-rgba";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-rgba/-/color-rgba-3.0.0.tgz";
        sha512 = "PPwZYkEY3M2THEHHV6Y95sGUie77S7X8v+h1r6LSAPF3/LL2xJ8duUXSrkic31Nzc4odPwHgUbiX/XuTYzQHQg==";
      };
    };
    "color-space-2.3.2" = {
      name = "color-space";
      packageName = "color-space";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-space/-/color-space-2.3.2.tgz";
        sha512 = "BcKnbOEsOarCwyoLstcoEztwT0IJxqqQkNwDuA3a65sICvvHL2yoeV13psoDFh5IuiOMnIOKdQDwB4Mk3BypiA==";
      };
    };
    "cronstrue-2.59.0" = {
      name = "cronstrue";
      packageName = "cronstrue";
      version = "2.59.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cronstrue/-/cronstrue-2.59.0.tgz";
        sha512 = "YKGmAy84hKH+hHIIER07VCAHf9u0Ldelx1uU6EBxsRPDXIA1m5fsKmJfyC3xBhw6cVC/1i83VdbL4PvepTrt8A==";
      };
    };
    "dedent-js-1.0.1" = {
      name = "dedent-js";
      packageName = "dedent-js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dedent-js/-/dedent-js-1.0.1.tgz";
        sha512 = "OUepMozQULMLUmhxS95Vudo0jb0UchLimi3+pQ2plj61Fcy8axbP9hbiD4Sz6DPqn6XG3kfmziVfQ1rSys5AJQ==";
      };
    };
    "defu-6.1.4" = {
      name = "defu";
      packageName = "defu";
      version = "6.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/defu/-/defu-6.1.4.tgz";
        sha512 = "mEQCMmwJu317oSz8CwdIOdwf3xMif1ttiM8LTufzc3g6kR+9Pe236twL8j3IYT1F7GfRgGcW6MWxzZjLIkuHIg==";
      };
    };
    "deprecation-2.3.1" = {
      name = "deprecation";
      packageName = "deprecation";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deprecation/-/deprecation-2.3.1.tgz";
        sha512 = "xmHIy4F3scKVwMsQ4WnVaS8bHOx0DmVwRywosKhaILI0ywMDWPtBSku2HNxRvF7jtwDRsoEwYQSfbxj8b7RlJQ==";
      };
    };
    "esm-env-1.2.2" = {
      name = "esm-env";
      packageName = "esm-env";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esm-env/-/esm-env-1.2.2.tgz";
        sha512 = "Epxrv+Nr/CaL4ZcFGPJIYLWFom+YeV1DqMLHJoEd9SYRxNbaFruBwfEX/kkHUJf55j2+TUbmDcmuilbP1TmXHA==";
      };
    };
    "esrap-2.1.3" = {
      name = "esrap";
      packageName = "esrap";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrap/-/esrap-2.1.3.tgz";
        sha512 = "T/Dhhv/QH+yYmiaLz9SA3PW+YyenlnRKDNdtlYJrSOBmNsH4nvPux+mTwx7p+wAedlJrGoZtXNI0a0MjQ2QkVg==";
      };
    };
    "fast-content-type-parse-2.0.1" = {
      name = "fast-content-type-parse";
      packageName = "fast-content-type-parse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-content-type-parse/-/fast-content-type-parse-2.0.1.tgz";
        sha512 = "nGqtvLrj5w0naR6tDPfB4cUmYCqouzyQiz6C5y/LtcDllJdrcc6WaWW6iXyIIOErTa/XRybj28aasdn4LkVk6Q==";
      };
    };
    "fzf-0.5.2" = {
      name = "fzf";
      packageName = "fzf";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fzf/-/fzf-0.5.2.tgz";
        sha512 = "Tt4kuxLXFKHy8KT40zwsUPUkg1CrsgY25FxA2U/j/0WgEDCk3ddc/zLTCCcbSHX9FcKtLuVaDGtGE/STWC+j3Q==";
      };
    };
    "gh-actions-language-server-0.0.3" = {
      name = "gh-actions-language-server";
      packageName = "gh-actions-language-server";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/gh-actions-language-server/-/gh-actions-language-server-0.0.3.tgz";
        sha512 = "T2ph7OoS0tnpWsxpvdiC5k9rrv5t7BMwZRJANrk4gZzvTZ1/rY1kpJQjVaiYeTrlj2fDgQh5fMwPqkxNaKIGdw==";
      };
    };
    "is-plain-object-5.0.0" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-5.0.0.tgz";
        sha512 = "VRSzKkbMm5jMDoKLbltAkFQ5Qr7VDiTFGXxYFXXowVj387GeGNOCsOH6Msy00SGZ3Fp84b1Naa1psqgcCIEP5Q==";
      };
    };
    "is-reference-3.0.3" = {
      name = "is-reference";
      packageName = "is-reference";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-reference/-/is-reference-3.0.3.tgz";
        sha512 = "ixkJoqQvAP88E6wLydLGGqCJsrFUnqoH6HnaczB8XmDH1oaWU+xxdptvikTgaEhtZ53Ky6YXiBuUI2WXLMCwjw==";
      };
    };
    "jiti-2.6.1" = {
      name = "jiti";
      packageName = "jiti";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-2.6.1.tgz";
        sha512 = "ekilCSN1jwRvIbgeg/57YFh8qQDNbwDb9xT/qu2DAHbFFZUicIl4ygVaAvzveMhMVr3LnpSKTNnwt8PoOfmKhQ==";
      };
    };
    "locate-character-3.0.0" = {
      name = "locate-character";
      packageName = "locate-character";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-character/-/locate-character-3.0.0.tgz";
        sha512 = "SW13ws7BjaeJ6p7Q6CO2nchbYEc3X3J6WrmTTDto7yMPqVSZTUyY5Tjbid+Ab8gLnATtygYtiDIJGQRRn2ZOiA==";
      };
    };
    "lru-cache-11.2.2" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "11.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-11.2.2.tgz";
        sha512 = "F9ODfyqML2coTIsQpSkRHnLSZMtkU8Q+mSfcaIyKwy58u+8k5nvAYeiNhsyMARvzNcXJ9QfWVrcPsC9e9rAxtg==";
      };
    };
    "magic-string-0.30.21" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.21.tgz";
        sha512 = "vd2F4YUyEXKGcLHoq+TEyCjxueSeHnFxyyjNp80yg0XV4vUhnDer/lvvlqM/arB5bXQN5K2/3oinyCRyx8T2CQ==";
      };
    };
    "node-fetch-2.7.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.7.0.tgz";
        sha512 = "c4FRfUm/dbcWZ7U+1Wq0AwCyFL+3nt2bEw05wfxSz+DWpWsitgmSgYmy2dQdWyKC1694ELPqMs/YzUSNozLt8A==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "quansync-0.2.11" = {
      name = "quansync";
      packageName = "quansync";
      version = "0.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/quansync/-/quansync-0.2.11.tgz";
        sha512 = "AifT7QEbW9Nri4tAwR5M/uzpBuqfZf+zwaEM/QkzEjj7NBuFD2rBuy0K3dE+8wltbezDV7JMA0WfnCPYRSYbXA==";
      };
    };
    "scule-1.3.0" = {
      name = "scule";
      packageName = "scule";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scule/-/scule-1.3.0.tgz";
        sha512 = "6FtHJEvt+pVMIB9IBY+IcCJ6Z5f1iQnytgyfKMhDKgmzYG+TeH/wx1y3l27rshSbLiSanrR9ffZDrEsmjlQF2g==";
      };
    };
    "svelte-5.43.14" = {
      name = "svelte";
      packageName = "svelte";
      version = "5.43.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-5.43.14.tgz";
        sha512 = "pHeUrp1A5S6RGaXhJB7PtYjL1VVjbVrJ2EfuAoPu9/1LeoMaJa/pcdCsCSb0gS4eUHAHnhCbUDxORZyvGK6kOQ==";
      };
    };
    "svelte2tsx-0.7.45" = {
      name = "svelte2tsx";
      packageName = "svelte2tsx";
      version = "0.7.45";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte2tsx/-/svelte2tsx-0.7.45.tgz";
        sha512 = "cSci+mYGygYBHIZLHlm/jYlEc1acjAHqaQaDFHdEBpUueM9kSTnPpvPtSl5VkJOU1qSJ7h1K+6F/LIUYiqC8VA==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha512 = "N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==";
      };
    };
    "typescript-5.9.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
        sha512 = "jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
      };
    };
    "typescript-svelte-plugin-0.3.50" = {
      name = "typescript-svelte-plugin";
      packageName = "typescript-svelte-plugin";
      version = "0.3.50";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-svelte-plugin/-/typescript-svelte-plugin-0.3.50.tgz";
        sha512 = "CD6jMNAYJwqCyQ5zZBDRuveeJvAgIogLwXMf5eXAl4K36wD8W+Npw49h6j5fXnpd7SKcG3uptGpeCGETED6WSA==";
      };
    };
    "unconfig-7.4.1" = {
      name = "unconfig";
      packageName = "unconfig";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unconfig/-/unconfig-7.4.1.tgz";
        sha512 = "uyQ7LElcGizrOGZyIq9KU+xkuEjcRf9IpmDTkCSYv5mEeZzrXSj6rb51C0L+WTedsmAoVxW9WKrLWhSwebIM9Q==";
      };
    };
    "unconfig-core-7.4.1" = {
      name = "unconfig-core";
      packageName = "unconfig-core";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unconfig-core/-/unconfig-core-7.4.1.tgz";
        sha512 = "Bp/bPZjV2Vl/fofoA2OYLSnw1Z0MOhCX7zHnVCYrazpfZvseBbGhwcNQMxsg185Mqh7VZQqK3C8hFG/Dyng+yA==";
      };
    };
    "universal-user-agent-6.0.1" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-6.0.1.tgz";
        sha512 = "yCzhz6FN2wU1NiiQRogkTQszlQSlpWaw8SvVegAc+bDxbzHgh1vX8uIe8OYyMH6DwH+sdTJsgMl36+mSMdRJIQ==";
      };
    };
    "universal-user-agent-7.0.3" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-7.0.3.tgz";
        sha512 = "TmnEAEAsBJVZM/AADELsK76llnwcf9vMKuPz8JflO1frO8Lchitr0fNaN9d+Ap0BjKtqWqd/J17qeDnXh8CL2A==";
      };
    };
    "unocss-language-server-0.1.8" = {
      name = "unocss-language-server";
      packageName = "unocss-language-server";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/unocss-language-server/-/unocss-language-server-0.1.8.tgz";
        sha512 = "PL9OqWQx3ehXZmOYEwZ42ZWXlC23M3VEDxJWuk4k1Z8FnFkiwm8ox7/NuctxqbLXtkmUouDRqEeZU27a2NZRGw==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-jsonrpc-8.2.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz";
        sha512 = "C+r0eKJUIfiDIfwJhria30+TYWPtuHJXHtI7J0YlOmKAo7ogxP20T0zxB7HZQIFhIyvoBPwWskjxrvAtfjyZfA==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-9.0.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-9.0.1.tgz";
        sha512 = "woByF3PDpkHFUreUa7Hos7+pUWdeWMXRd26+ZX2A8cFx6v/JPTtd4/uN0/jB6XQHYaOlHbio03NTHCqrgG5n7g==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-protocol-3.17.5" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz";
        sha512 = "mb1bvRJN8SVznADSGWM9u/b07H7Ecg0I3OgXDuLdn307rl/J3A9YD6/eYOssqhecL27hK1IPZAsaqh00i/Jljg==";
      };
    };
    "vscode-languageserver-textdocument-1.0.12" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.12.tgz";
        sha512 = "cxWNPesCnQCcMPeenjKKsOCKQZ/L6Tv19DTRIGuLWe32lyzWhihGVJ/rcckZXJxfdKCFvRLS3fpBIsV/ZGX4zA==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha512 = "2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha512 = "saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yaml-2.8.1" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.8.1.tgz";
        sha512 = "lcYcMxX2PO9XMGvAJkJ3OsNMw+/7FKes7/hgerGUYWIoWu5j/+YQqcZr5JnPZWzOsEBgMbSbiSTn/dv/69Mkpw==";
      };
    };
    "zimmerframe-1.1.4" = {
      name = "zimmerframe";
      packageName = "zimmerframe";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/zimmerframe/-/zimmerframe-1.1.4.tgz";
        sha512 = "B58NGBEoc8Y9MWWCQGl/gq9xBCe4IiKM0a2x7GZdQKOW5Exr8S1W24J6OgM1njK8xCRGvAJIL/MxXHf6SkmQKQ==";
      };
    };
  };
  args = {
    name = "node_servers";
    packageName = "node_servers";
    src = ./.;
    dependencies = [
      sources."@actions/expressions-0.3.20"
      (
        sources."@actions/languageserver-0.3.20"
        // {
          dependencies = [
            sources."@octokit/auth-token-5.1.2"
            (
              sources."@octokit/core-6.1.6"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            (
              sources."@octokit/endpoint-10.1.4"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            (
              sources."@octokit/graphql-8.2.2"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            sources."@octokit/openapi-types-25.1.0"
            (
              sources."@octokit/plugin-paginate-rest-11.6.0"
              // {
                dependencies = [
                  sources."@octokit/openapi-types-24.2.0"
                  sources."@octokit/types-13.10.0"
                ];
              }
            )
            sources."@octokit/plugin-request-log-5.3.1"
            (
              sources."@octokit/plugin-rest-endpoint-methods-13.5.0"
              // {
                dependencies = [
                  sources."@octokit/openapi-types-24.2.0"
                  sources."@octokit/types-13.10.0"
                ];
              }
            )
            (
              sources."@octokit/request-9.2.4"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            (
              sources."@octokit/request-error-6.1.8"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            sources."@octokit/rest-21.1.1"
            sources."before-after-hook-3.0.2"
            sources."universal-user-agent-7.0.3"
          ];
        }
      )
      sources."@actions/languageservice-0.3.20"
      sources."@actions/workflow-parser-0.3.20"
      sources."@jridgewell/gen-mapping-0.3.13"
      sources."@jridgewell/remapping-2.3.5"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/sourcemap-codec-1.5.5"
      sources."@jridgewell/trace-mapping-0.3.31"
      sources."@octokit/auth-token-3.0.4"
      sources."@octokit/core-4.2.4"
      sources."@octokit/endpoint-7.0.6"
      sources."@octokit/graphql-5.0.6"
      sources."@octokit/openapi-types-18.1.1"
      sources."@octokit/plugin-paginate-rest-6.1.2"
      sources."@octokit/plugin-request-log-1.0.4"
      (
        sources."@octokit/plugin-rest-endpoint-methods-7.2.3"
        // {
          dependencies = [
            sources."@octokit/types-10.0.0"
          ];
        }
      )
      sources."@octokit/request-6.2.8"
      sources."@octokit/request-error-3.0.3"
      sources."@octokit/rest-19.0.13"
      sources."@octokit/tsconfig-1.0.2"
      sources."@octokit/types-9.3.2"
      sources."@quansync/fs-0.1.5"
      sources."@sveltejs/acorn-typescript-1.0.7"
      sources."@types/estree-1.0.8"
      (
        sources."@unocss/autocomplete-66.5.9"
        // {
          dependencies = [
            sources."lru-cache-11.2.2"
          ];
        }
      )
      sources."@unocss/config-66.5.9"
      sources."@unocss/core-66.5.9"
      sources."@unocss/extractor-arbitrary-variants-66.5.9"
      sources."@unocss/preset-mini-66.5.9"
      sources."@unocss/preset-wind3-66.5.9"
      sources."@unocss/rule-utils-66.5.9"
      sources."acorn-8.15.0"
      sources."aria-query-5.3.2"
      sources."axobject-query-4.1.0"
      sources."before-after-hook-2.2.3"
      sources."clsx-2.1.1"
      (
        sources."color-parse-2.0.2"
        // {
          dependencies = [
            sources."color-name-2.1.0"
          ];
        }
      )
      sources."color-rgba-3.0.0"
      sources."color-space-2.3.2"
      sources."cronstrue-2.59.0"
      sources."dedent-js-1.0.1"
      sources."defu-6.1.4"
      sources."deprecation-2.3.1"
      sources."esm-env-1.2.2"
      sources."esrap-2.1.3"
      sources."fast-content-type-parse-2.0.1"
      sources."fzf-0.5.2"
      sources."gh-actions-language-server-0.0.3"
      sources."is-plain-object-5.0.0"
      sources."is-reference-3.0.3"
      sources."jiti-2.6.1"
      sources."locate-character-3.0.0"
      sources."magic-string-0.30.21"
      sources."node-fetch-2.7.0"
      sources."once-1.4.0"
      sources."quansync-0.2.11"
      sources."scule-1.3.0"
      sources."svelte-5.43.14"
      sources."svelte2tsx-0.7.45"
      sources."tr46-0.0.3"
      sources."typescript-5.9.3"
      sources."typescript-svelte-plugin-0.3.50"
      sources."unconfig-7.4.1"
      sources."unconfig-core-7.4.1"
      sources."universal-user-agent-6.0.1"
      (
        sources."unocss-language-server-0.1.8"
        // {
          dependencies = [
            sources."vscode-jsonrpc-8.2.0"
            sources."vscode-languageserver-9.0.1"
            sources."vscode-languageserver-protocol-3.17.5"
          ];
        }
      )
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      (
        sources."vscode-languageserver-protocol-3.17.3"
        // {
          dependencies = [
            sources."vscode-languageserver-types-3.17.3"
          ];
        }
      )
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-uri-3.1.0"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
      sources."wrappy-1.0.2"
      sources."yaml-2.8.1"
      sources."zimmerframe-1.1.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (
    lib.overrideExisting args {
      src = stdenv.mkDerivation {
        name = args.name + "-package-json";
        src = nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ] args.src;
        dontBuild = true;
        installPhase = "mkdir -p $out; cp -r ./* $out;";
      };
    }
  );
}
