# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = {
    "@actions/expressions-0.3.20" = {
      name = "_at_actions_slash_expressions";
      packageName = "@actions/expressions";
      version = "0.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/expressions/-/expressions-0.3.20.tgz";
        sha512 = "AZ8lfVjBXD2K6jzkLj2CsLx9ppI9CzqnfdH4J3ZSp1pRWHL3bURpqyTs8zg2tCJb7zoR8Gsw3DTxPKfvGwQKrA==";
      };
    };
    "@actions/languageserver-0.3.20" = {
      name = "_at_actions_slash_languageserver";
      packageName = "@actions/languageserver";
      version = "0.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/languageserver/-/languageserver-0.3.20.tgz";
        sha512 = "UI1Qi/SJzrMpqhwd6AfyK9rMYy71ueIFtHjLmNxEqaDMRUj06/LUaE9F2mWM29xOD3CVs1gZrGpQtuIY3QGxtg==";
      };
    };
    "@actions/languageservice-0.3.20" = {
      name = "_at_actions_slash_languageservice";
      packageName = "@actions/languageservice";
      version = "0.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/languageservice/-/languageservice-0.3.20.tgz";
        sha512 = "s8DiUNKew9+IdRVqu2jxVmpPU7kIegQ9vSfhXxBbGkFLqkJANhg+M6tt3oEwgTtaUH1r44rccfrocATZZNaH5A==";
      };
    };
    "@actions/workflow-parser-0.3.20" = {
      name = "_at_actions_slash_workflow-parser";
      packageName = "@actions/workflow-parser";
      version = "0.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/workflow-parser/-/workflow-parser-0.3.20.tgz";
        sha512 = "qhIzkiTiyiYX0CaIR+SS5Z0g7BMqS6VIC0t4GZH8lVGbK6Yw+0TpSX8iTFySfZMMoVpSCFy6uBxekskvBpkqEQ==";
      };
    };
    "@azu/format-text-1.0.2" = {
      name = "_at_azu_slash_format-text";
      packageName = "@azu/format-text";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@azu/format-text/-/format-text-1.0.2.tgz";
        sha512 = "Swi4N7Edy1Eqq82GxgEECXSSLyn6GOb5htRFPzBDdUkECGXtlf12ynO5oJSpWKPwCaUssOu7NfhDcCWpIC6Ywg==";
      };
    };
    "@azu/style-format-1.0.1" = {
      name = "_at_azu_slash_style-format";
      packageName = "@azu/style-format";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@azu/style-format/-/style-format-1.0.1.tgz";
        sha512 = "AHcTojlNBdD/3/KxIKlg8sxIWHfOtQszLvOpagLTO+bjC3u7SAszu1lf//u7JJC50aUSH+BVWDD/KvaA6Gfn5g==";
      };
    };
    "@babel/code-frame-7.27.1" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.27.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.27.1.tgz";
        sha512 = "cjQ7ZlQ0Mv3b47hABuTevyTuYN4i+loJKGeV9flcCgIK37cCXRh+L1bd3iBHlynerhQ7BhCkn2BPbQUL+rGqFg==";
      };
    };
    "@babel/helper-validator-identifier-7.28.5" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.28.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.28.5.tgz";
        sha512 = "qSs4ifwzKJSV39ucNjsvc6WVHs6b7S03sOh2OcHF9UHfVPqWWALUsNUVzhSBiItjRZoLHx7nIarVjqKVusUZ1Q==";
      };
    };
    "@jridgewell/gen-mapping-0.3.13" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz";
        sha512 = "2kkt/7niJ6MgEPxF0bYdQ6etZaA+fQvDcLKckhy1yIQOzaoKjBBjSj63/aLVjYE3qhRt5dvM+uUyfCg6UKCBbA==";
      };
    };
    "@jridgewell/remapping-2.3.5" = {
      name = "_at_jridgewell_slash_remapping";
      packageName = "@jridgewell/remapping";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/remapping/-/remapping-2.3.5.tgz";
        sha512 = "LI9u/+laYG4Ds1TDKSJW2YPrIlcVYOwi2fUC6xB43lueCjgxV4lffOCZCtYFiH6TNOX+tQKXx97T4IKHbhyHEQ==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.5" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
        sha512 = "cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
      };
    };
    "@jridgewell/trace-mapping-0.3.31" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.31.tgz";
        sha512 = "zzNR+SdQSDJzc8joaeP8QQoCQr8NuYx2dIIytl1QeBEZHJ9uW6hebsrYgbz8hJwUQao3TWCMtmfV8Nu1twOLAw==";
      };
    };
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.8" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
        sha512 = "oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      };
    };
    "@octokit/auth-token-3.0.4" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-3.0.4.tgz";
        sha512 = "TWFX7cZF2LXoCvdmJWY7XVPi74aSY0+FfBZNSXEXFkMpjcqsQwDSYVv5FhRFaI0V1ECnwbz4j59T/G+rXNWaIQ==";
      };
    };
    "@octokit/auth-token-5.1.2" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-5.1.2.tgz";
        sha512 = "JcQDsBdg49Yky2w2ld20IHAlwr8d/d8N6NiOXbtuoPCqzbsiJgF633mVUw3x4mo0H5ypataQIX7SFu3yy44Mpw==";
      };
    };
    "@octokit/core-4.2.4" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-4.2.4.tgz";
        sha512 = "rYKilwgzQ7/imScn3M9/pFfUf4I1AZEH3KhyJmtPdE2zfaXAn2mFfUy4FbKewzc2We5y/LlKLj36fWJLKC2SIQ==";
      };
    };
    "@octokit/core-6.1.6" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "6.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-6.1.6.tgz";
        sha512 = "kIU8SLQkYWGp3pVKiYzA5OSaNF5EE03P/R8zEmmrG6XwOg5oBjXyQVVIauQ0dgau4zYhpZEhJrvIYt6oM+zZZA==";
      };
    };
    "@octokit/endpoint-10.1.4" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "10.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-10.1.4.tgz";
        sha512 = "OlYOlZIsfEVZm5HCSR8aSg02T2lbUWOsCQoPKfTXJwDzcHQBrVBGdGXb89dv2Kw2ToZaRtudp8O3ZIYoaOjKlA==";
      };
    };
    "@octokit/endpoint-7.0.6" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-7.0.6.tgz";
        sha512 = "5L4fseVRUsDFGR00tMWD/Trdeeihn999rTMGRMC1G/Ldi1uWlWJzI98H4Iak5DB/RVvQuyMYKqSK/R6mbSOQyg==";
      };
    };
    "@octokit/graphql-5.0.6" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "5.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-5.0.6.tgz";
        sha512 = "Fxyxdy/JH0MnIB5h+UQ3yCoh1FG4kWXfFKkpWqjZHw/p+Kc8Y44Hu/kCgNBT6nU1shNumEchmW/sUO1JuQnPcw==";
      };
    };
    "@octokit/graphql-8.2.2" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "8.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-8.2.2.tgz";
        sha512 = "Yi8hcoqsrXGdt0yObxbebHXFOiUA+2v3n53epuOg1QUgOB6c4XzvisBNVXJSl8RYA5KrDuSL2yq9Qmqe5N0ryA==";
      };
    };
    "@octokit/openapi-types-18.1.1" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "18.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-18.1.1.tgz";
        sha512 = "VRaeH8nCDtF5aXWnjPuEMIYf1itK/s3JYyJcWFJT8X9pSNnBtriDf7wlEWsGuhPLl4QIH4xM8fqTXDwJ3Mu6sw==";
      };
    };
    "@octokit/openapi-types-24.2.0" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "24.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-24.2.0.tgz";
        sha512 = "9sIH3nSUttelJSXUrmGzl7QUBFul0/mB8HRYl3fOlgHbIWG+WnYDXU3v/2zMtAvuzZ/ed00Ei6on975FhBfzrg==";
      };
    };
    "@octokit/openapi-types-25.1.0" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "25.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-25.1.0.tgz";
        sha512 = "idsIggNXUKkk0+BExUn1dQ92sfysJrje03Q0bv0e+KPLrvyqZF8MnBpFz8UNfYDwB3Ie7Z0TByjWfzxt7vseaA==";
      };
    };
    "@octokit/plugin-paginate-rest-11.6.0" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "11.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-11.6.0.tgz";
        sha512 = "n5KPteiF7pWKgBIBJSk8qzoZWcUkza2O6A0za97pMGVrGfPdltxrfmfF5GucHYvHGZD8BdaZmmHGz5cX/3gdpw==";
      };
    };
    "@octokit/plugin-paginate-rest-6.1.2" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "6.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-6.1.2.tgz";
        sha512 = "qhrmtQeHU/IivxucOV1bbI/xZyC/iOBhclokv7Sut5vnejAIAEXVcGQeRpQlU39E0WwK9lNvJHphHri/DB6lbQ==";
      };
    };
    "@octokit/plugin-request-log-1.0.4" = {
      name = "_at_octokit_slash_plugin-request-log";
      packageName = "@octokit/plugin-request-log";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-request-log/-/plugin-request-log-1.0.4.tgz";
        sha512 = "mLUsMkgP7K/cnFEw07kWqXGF5LKrOkD+lhCrKvPHXWDywAwuDUeDwWBpc69XK3pNX0uKiVt8g5z96PJ6z9xCFA==";
      };
    };
    "@octokit/plugin-request-log-5.3.1" = {
      name = "_at_octokit_slash_plugin-request-log";
      packageName = "@octokit/plugin-request-log";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-request-log/-/plugin-request-log-5.3.1.tgz";
        sha512 = "n/lNeCtq+9ofhC15xzmJCNKP2BWTv8Ih2TTy+jatNCCq/gQP/V7rK3fjIfuz0pDWDALO/o/4QY4hyOF6TQQFUw==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-13.5.0" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "13.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-13.5.0.tgz";
        sha512 = "9Pas60Iv9ejO3WlAX3maE1+38c5nqbJXV5GrncEfkndIpZrJ/WPMRd2xYDcPPEt5yzpxcjw9fWNoPhsSGzqKqw==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-7.2.3" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-7.2.3.tgz";
        sha512 = "I5Gml6kTAkzVlN7KCtjOM+Ruwe/rQppp0QU372K1GP7kNOYEKe8Xn5BW4sE62JAHdwpq95OQK/qGNyKQMUzVgA==";
      };
    };
    "@octokit/request-6.2.8" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "6.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-6.2.8.tgz";
        sha512 = "ow4+pkVQ+6XVVsekSYBzJC0VTVvh/FCTUUgTsboGq+DTeWdyIFV8WSCdo0RIxk6wSkBTHqIK1mYuY7nOBXOchw==";
      };
    };
    "@octokit/request-9.2.4" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-9.2.4.tgz";
        sha512 = "q8ybdytBmxa6KogWlNa818r0k1wlqzNC+yNkcQDECHvQo8Vmstrg18JwqJHdJdUiHD2sjlwBgSm9kHkOKe2iyA==";
      };
    };
    "@octokit/request-error-3.0.3" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-3.0.3.tgz";
        sha512 = "crqw3V5Iy2uOU5Np+8M/YexTlT8zxCfI+qu+LxUB7SZpje4Qmx3mub5DfEKSO8Ylyk0aogi6TYdf6kxzh2BguQ==";
      };
    };
    "@octokit/request-error-6.1.8" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "6.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-6.1.8.tgz";
        sha512 = "WEi/R0Jmq+IJKydWlKDmryPcmdYSVjL3ekaiEL1L9eo1sUnqMJ+grqmC9cjk7CA7+b2/T397tO5d8YLOH3qYpQ==";
      };
    };
    "@octokit/rest-19.0.13" = {
      name = "_at_octokit_slash_rest";
      packageName = "@octokit/rest";
      version = "19.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/rest/-/rest-19.0.13.tgz";
        sha512 = "/EzVox5V9gYGdbAI+ovYj3nXQT1TtTHRT+0eZPcuC05UFSWO3mdO9UY1C0i2eLF9Un1ONJkAk+IEtYGAC+TahA==";
      };
    };
    "@octokit/rest-21.1.1" = {
      name = "_at_octokit_slash_rest";
      packageName = "@octokit/rest";
      version = "21.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/rest/-/rest-21.1.1.tgz";
        sha512 = "sTQV7va0IUVZcntzy1q3QqPm/r8rWtDCqpRAmb8eXXnKkjoQEtFe3Nt5GTVsHft+R6jJoHeSiVLcgcvhtue/rg==";
      };
    };
    "@octokit/tsconfig-1.0.2" = {
      name = "_at_octokit_slash_tsconfig";
      packageName = "@octokit/tsconfig";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/tsconfig/-/tsconfig-1.0.2.tgz";
        sha512 = "I0vDR0rdtP8p2lGMzvsJzbhdOWy405HcGovrspJ8RRibHnyRgggUSNO5AIox5LmqiwmatHKYsvj6VGFHkqS7lA==";
      };
    };
    "@octokit/types-10.0.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-10.0.0.tgz";
        sha512 = "Vm8IddVmhCgU1fxC1eyinpwqzXPEYu0NrYzD3YZjlGjyftdLBTeqNblRC0jmJmgxbJIsQlyogVeGnrNaaMVzIg==";
      };
    };
    "@octokit/types-13.10.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "13.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-13.10.0.tgz";
        sha512 = "ifLaO34EbbPj0Xgro4G5lP5asESjwHracYJvVaPIyXMuiuXLlhic3S47cBdTb+jfODkTE5YtGCLt3Ay3+J97sA==";
      };
    };
    "@octokit/types-14.1.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-14.1.0.tgz";
        sha512 = "1y6DgTy8Jomcpu33N+p5w58l6xyt55Ar2I91RPiIA0xCJBXyUAhXCcmZaDWSANiha7R9a6qJJ2CRomGPZ6f46g==";
      };
    };
    "@octokit/types-9.3.2" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "9.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-9.3.2.tgz";
        sha512 = "D4iHGTdAnEEVsB8fl95m1hiz7D5YiRdQ9b/OEb3BYRVwbLsGHcRVPz+u+BgRLNk0Q0/4iZCBqDN96j2XNxfXrA==";
      };
    };
    "@quansync/fs-0.1.5" = {
      name = "_at_quansync_slash_fs";
      packageName = "@quansync/fs";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@quansync/fs/-/fs-0.1.5.tgz";
        sha512 = "lNS9hL2aS2NZgNW7BBj+6EBl4rOf8l+tQ0eRY6JWCI8jI2kc53gSoqbjojU0OnAWhzoXiOjFyGsHcDGePB3lhA==";
      };
    };
    "@secretlint/config-creator-8.5.0" = {
      name = "_at_secretlint_slash_config-creator";
      packageName = "@secretlint/config-creator";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/config-creator/-/config-creator-8.5.0.tgz";
        sha512 = "y+xezycryTu9t5CDYyfLHu+1TPgINXTa2Xy/N9hLKiLmF288Sfcwk1j8q98FioaEGCEbUHEgeqaRVJ0rDYdxMQ==";
      };
    };
    "@secretlint/config-loader-8.5.0" = {
      name = "_at_secretlint_slash_config-loader";
      packageName = "@secretlint/config-loader";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/config-loader/-/config-loader-8.5.0.tgz";
        sha512 = "lOtXUzyN3Whwb/hShfYmLe1qwpG3u7F2UqNXhSqQh22QWms0IXQEhVEf84PWgQd2KT5Ng3aIJKXUdyYwdP0PXA==";
      };
    };
    "@secretlint/core-8.5.0" = {
      name = "_at_secretlint_slash_core";
      packageName = "@secretlint/core";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/core/-/core-8.5.0.tgz";
        sha512 = "thSk9lGLqtyKheL2KivgmQQ8QF6WQwm6Lbj74P2Nw2OmzAfRVfqMUIdI0OUojWugnNU0L6DMakcEowQ3tooqYg==";
      };
    };
    "@secretlint/formatter-8.5.0" = {
      name = "_at_secretlint_slash_formatter";
      packageName = "@secretlint/formatter";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/formatter/-/formatter-8.5.0.tgz";
        sha512 = "BdhCxmlYNeLGSnke2iolDb2yCFNUsPwkziSn2u3ARGEC687FqhwkcSR4DGOFngO6L744btN59V4Xm0G+W8GCXg==";
      };
    };
    "@secretlint/node-8.5.0" = {
      name = "_at_secretlint_slash_node";
      packageName = "@secretlint/node";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/node/-/node-8.5.0.tgz";
        sha512 = "8nPVHqWjPcJJIPQmkzDAVjOCjucHJUVYpXmxyPvprtnZ+ferx/oc0PNoM0gxOYiBxagjG7kYq0HWpYEHChy16A==";
      };
    };
    "@secretlint/profiler-8.5.0" = {
      name = "_at_secretlint_slash_profiler";
      packageName = "@secretlint/profiler";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/profiler/-/profiler-8.5.0.tgz";
        sha512 = "f8IAEtI5/Cn4moeCUD5zrM88KsSPkuOj3ZtJBpDsv7cXbmNS4bKFmn+eC943fMgNr7gHb2HBDjllH+uhBLG8Sg==";
      };
    };
    "@secretlint/resolver-8.5.0" = {
      name = "_at_secretlint_slash_resolver";
      packageName = "@secretlint/resolver";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/resolver/-/resolver-8.5.0.tgz";
        sha512 = "xa4eBR1UbH/dieZEdZ2+cor9mT6IYgFJWfLGEH+XqFl0EmxnIg/RUjOMV2HvZvmmA3tRjhyP1ko6CEsYaBoULQ==";
      };
    };
    "@secretlint/secretlint-rule-preset-recommend-8.5.0" = {
      name = "_at_secretlint_slash_secretlint-rule-preset-recommend";
      packageName = "@secretlint/secretlint-rule-preset-recommend";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/secretlint-rule-preset-recommend/-/secretlint-rule-preset-recommend-8.5.0.tgz";
        sha512 = "jfvCI2nbQ/k53Ffzm/dEGxV6dW8dzMRAhImZWLc3LBkIjRv3ZcMljvbjqDsrM614QF1BGMWT7D+JCBFmzcfEFA==";
      };
    };
    "@secretlint/source-creator-8.5.0" = {
      name = "_at_secretlint_slash_source-creator";
      packageName = "@secretlint/source-creator";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/source-creator/-/source-creator-8.5.0.tgz";
        sha512 = "z0bRqWnB3sL/CbD0wAdl0bBUVJ78njN+GQ5lsvngf21Ap5Hpc4pdU1EIKys99cxTu6cCIp72J3xhPWk4UiI6UA==";
      };
    };
    "@secretlint/types-8.5.0" = {
      name = "_at_secretlint_slash_types";
      packageName = "@secretlint/types";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@secretlint/types/-/types-8.5.0.tgz";
        sha512 = "Bz1RziuGbIJKO9dyO0RWysKxGZvyGydo0tMygri96z2mPA9ijCzYAbHmYrLdin2Ce77p6HYSxD48iXelh9+Ytw==";
      };
    };
    "@sindresorhus/merge-streams-2.3.0" = {
      name = "_at_sindresorhus_slash_merge-streams";
      packageName = "@sindresorhus/merge-streams";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sindresorhus/merge-streams/-/merge-streams-2.3.0.tgz";
        sha512 = "LtoMMhxAlorcGhmFYI+LhPgbPZCkgP6ra1YL604EeF6U98pLlQ3iWIGMdWSC+vWmPBWBNgmDBAhnAobLROJmwg==";
      };
    };
    "@sveltejs/acorn-typescript-1.0.7" = {
      name = "_at_sveltejs_slash_acorn-typescript";
      packageName = "@sveltejs/acorn-typescript";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/acorn-typescript/-/acorn-typescript-1.0.7.tgz";
        sha512 = "znp1A/Y1Jj4l/Zy7PX5DZKBE0ZNY+5QBngiE21NJkfSTyzzC5iKNWOtwFXKtIrn7MXEFBck4jD95iBNkGjK92Q==";
      };
    };
    "@textlint/ast-node-types-14.8.4" = {
      name = "_at_textlint_slash_ast-node-types";
      packageName = "@textlint/ast-node-types";
      version = "14.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@textlint/ast-node-types/-/ast-node-types-14.8.4.tgz";
        sha512 = "+fI7miec/r9VeniFV9ppL4jRCmHNsTxieulTUf/4tvGII3db5hGriKHC4p/diq1SkQ9Sgs7kg6UyydxZtpTz1Q==";
      };
    };
    "@textlint/linter-formatter-14.8.4" = {
      name = "_at_textlint_slash_linter-formatter";
      packageName = "@textlint/linter-formatter";
      version = "14.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@textlint/linter-formatter/-/linter-formatter-14.8.4.tgz";
        sha512 = "sZ0UfYRDBNHnfMVBqLqqYnqTB7Ec169ljlmo+SEHR1T+dHUPYy1/DZK4p7QREXlBSFL4cnkswETCbc9xRodm4Q==";
      };
    };
    "@textlint/module-interop-14.8.4" = {
      name = "_at_textlint_slash_module-interop";
      packageName = "@textlint/module-interop";
      version = "14.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@textlint/module-interop/-/module-interop-14.8.4.tgz";
        sha512 = "1LdPYLAVpa27NOt6EqvuFO99s4XLB0c19Hw9xKSG6xQ1K82nUEyuWhzTQKb3KJ5Qx7qj14JlXZLfnEuL6A16Bw==";
      };
    };
    "@textlint/resolver-14.8.4" = {
      name = "_at_textlint_slash_resolver";
      packageName = "@textlint/resolver";
      version = "14.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@textlint/resolver/-/resolver-14.8.4.tgz";
        sha512 = "nMDOgDAVwNU9ommh+Db0U+MCMNDPbQ/1HBNjbnHwxZkCpcT6hsAJwBe38CW/DtWVUv8yeR4R40IYNPT84srNwA==";
      };
    };
    "@textlint/types-14.8.4" = {
      name = "_at_textlint_slash_types";
      packageName = "@textlint/types";
      version = "14.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@textlint/types/-/types-14.8.4.tgz";
        sha512 = "9nyY8vVXlr8hHKxa6+37omJhXWCwovMQcgMteuldYd4dOxGm14AK2nXdkgtKEUQnzLGaXy46xwLCfhQy7V7/YA==";
      };
    };
    "@types/estree-1.0.8" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz";
        sha512 = "dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
      };
    };
    "@types/normalize-package-data-2.4.4" = {
      name = "_at_types_slash_normalize-package-data";
      packageName = "@types/normalize-package-data";
      version = "2.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/normalize-package-data/-/normalize-package-data-2.4.4.tgz";
        sha512 = "37i+OaWTh9qeK4LSHPsyRC7NahnGotNuZvjLSgcPzblpHB3rrCJxAOgI5gCdKm7coonsaX1Of0ILiTcnZjbfxA==";
      };
    };
    "@unocss/autocomplete-66.5.9" = {
      name = "_at_unocss_slash_autocomplete";
      packageName = "@unocss/autocomplete";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/autocomplete/-/autocomplete-66.5.9.tgz";
        sha512 = "CyWob9D4nrkWWctaIXFt62kHGF7C5u1LK0NlvzEr/6qdpA+YOTlFRYCLI3E8+hJU/xOYxX12hNE9j2dtPOj7Mw==";
      };
    };
    "@unocss/config-66.5.9" = {
      name = "_at_unocss_slash_config";
      packageName = "@unocss/config";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/config/-/config-66.5.9.tgz";
        sha512 = "M8O0Z+6iCXuQOz/quaKueSb2cmN7cP9JGWdAH2E+qFD8txljaY88tNL4OwFZtO9GjhT2f/pEsLoEOAtAo1xT6g==";
      };
    };
    "@unocss/core-66.5.9" = {
      name = "_at_unocss_slash_core";
      packageName = "@unocss/core";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/core/-/core-66.5.9.tgz";
        sha512 = "0ch1dN1AJFX+QCxaQR6WLfWqr8PHt7U/wqSTm5vdLXTsm96R7ggCGMs360TiDMimDUvXak6gka+y/6wdQBf8/A==";
      };
    };
    "@unocss/extractor-arbitrary-variants-66.5.9" = {
      name = "_at_unocss_slash_extractor-arbitrary-variants";
      packageName = "@unocss/extractor-arbitrary-variants";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/extractor-arbitrary-variants/-/extractor-arbitrary-variants-66.5.9.tgz";
        sha512 = "b+D6HbtN4hpGcThdJ8IVPl3xXdNN//Rw+WhyIuRdjwCPMsOfLnEqehPm1f5Rcc+xfFwxYJwC35SZnoBSrRMULg==";
      };
    };
    "@unocss/preset-mini-66.5.9" = {
      name = "_at_unocss_slash_preset-mini";
      packageName = "@unocss/preset-mini";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-mini/-/preset-mini-66.5.9.tgz";
        sha512 = "5SxMTT8kRi+SFNfTKUvFBA4E/4H5BwD5RPNeIbrNlHdeltK8rwCMpXWu5AihNR1kKt5JBBqe/8m0UdoZzAK0+A==";
      };
    };
    "@unocss/preset-wind3-66.5.9" = {
      name = "_at_unocss_slash_preset-wind3";
      packageName = "@unocss/preset-wind3";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-wind3/-/preset-wind3-66.5.9.tgz";
        sha512 = "eT23SDqksr6LVzkJLDkGGNIBpRevMHIrretM8VNI7PECJEcpFwX9sgWn3yxAsqy5+0hJXuvFBc9BRUN6sHl5hQ==";
      };
    };
    "@unocss/rule-utils-66.5.9" = {
      name = "_at_unocss_slash_rule-utils";
      packageName = "@unocss/rule-utils";
      version = "66.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/rule-utils/-/rule-utils-66.5.9.tgz";
        sha512 = "ZdtWqbOaNQLf6NFhcEkvaBf0fjm5GZP5NV/plmQEqK6ehe1TTpaqOtO0LBFD2BUy72oXlcsFnvdgWt/CpL6FLg==";
      };
    };
    "acorn-8.15.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
        sha512 = "NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      };
    };
    "aggregate-error-3.1.0" = {
      name = "aggregate-error";
      packageName = "aggregate-error";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aggregate-error/-/aggregate-error-3.1.0.tgz";
        sha512 = "4I7Td01quW/RpocfNayFdFVk1qSuoh0E7JrbRJ16nH01HhKFQ88INq9Sd+nd72zqRySlr9BmDA8xlEJ6vJMrYA==";
      };
    };
    "ajv-8.17.1" = {
      name = "ajv";
      packageName = "ajv";
      version = "8.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-8.17.1.tgz";
        sha512 = "B/gBuNg5SiMTrPkC+A2+cW0RszwxYmn6VYxB/inlBStS5nx6xHIt/ehKRhIMhqusl7a8LjQoZnjCs5vhwxOQ1g==";
      };
    };
    "ansi-escapes-4.3.2" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-4.3.2.tgz";
        sha512 = "gKXj5ALrKWQLsYG9jlTRmR/xKluxHV+Z9QEwNIgCfM1/uwPMCuzVVnh5mwTd+OuBZcwSIMbqssNWRm1lE51QaQ==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "aria-query-5.3.2" = {
      name = "aria-query";
      packageName = "aria-query";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-query/-/aria-query-5.3.2.tgz";
        sha512 = "COROpnaoap1E2F000S62r6A60uHZnmlvomhfyT2DlTcrY1OrBKn2UhH7qn5wTC9zMvD0AY7csdPSNwKP+7WiQw==";
      };
    };
    "astral-regex-2.0.0" = {
      name = "astral-regex";
      packageName = "astral-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/astral-regex/-/astral-regex-2.0.0.tgz";
        sha512 = "Z7tMw1ytTXt5jqMcOP+OQteU1VuNK9Y02uuJtKQ1Sv69jXQKKg5cibLwGJow8yzZP+eAc18EmLGPal0bp36rvQ==";
      };
    };
    "axobject-query-4.1.0" = {
      name = "axobject-query";
      packageName = "axobject-query";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axobject-query/-/axobject-query-4.1.0.tgz";
        sha512 = "qIj0G9wZbMGNLjLmg1PT6v2mE9AH2zlnADJD/2tC6E00hgmhUOfEB6greHPAfLRSufHqROIUTkw6E+M3lH0PTQ==";
      };
    };
    "before-after-hook-2.2.3" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-2.2.3.tgz";
        sha512 = "NzUnlZexiaH/46WDhANlyR2bXRopNg4F/zuSA3OpZnllCUgRaOF2znDioDWrmbNVsuZk6l9pMquQB38cfBZwkQ==";
      };
    };
    "before-after-hook-3.0.2" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-3.0.2.tgz";
        sha512 = "Nik3Sc0ncrMK4UUdXQmAnRtzmNQTAAXmXIopizwZ1W1t8QmfJj+zL4OA2I7XPTPW5z5TDqv4hRo/JzouDJnX3A==";
      };
    };
    "binaryextensions-4.19.0" = {
      name = "binaryextensions";
      packageName = "binaryextensions";
      version = "4.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binaryextensions/-/binaryextensions-4.19.0.tgz";
        sha512 = "DRxnVbOi/1OgA5pA9EDiRT8gvVYeqfuN7TmPfLyt6cyho3KbHCi3EtDQf39TTmGDrR5dZ9CspdXhPkL/j/WGbg==";
      };
    };
    "boundary-2.0.0" = {
      name = "boundary";
      packageName = "boundary";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boundary/-/boundary-2.0.0.tgz";
        sha512 = "rJKn5ooC9u8q13IMCrW0RSp31pxBCHE3y9V/tp3TdWSLf8Em3p6Di4NBpfzbJge9YjjFEsD0RtFEjtvHL5VyEA==";
      };
    };
    "braces-3.0.3" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
        sha512 = "yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "clean-stack-2.2.0" = {
      name = "clean-stack";
      packageName = "clean-stack";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-stack/-/clean-stack-2.2.0.tgz";
        sha512 = "4diC9HaTE+KRAMWhDhrGOECgWZxoevMc5TlkObMqNSsVU62PYzXZ/SMTjzyGAFF1YusgxGcSWTEXBhp0CPwQ1A==";
      };
    };
    "clsx-2.1.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-2.1.1.tgz";
        sha512 = "eYm0QWBtUrBWZWG0d386OGAw16Z995PiOVo2B7bjWSbHedGl5e0ZWaq65kOGgUSNesEIDkB9ISbTg/JK9dhCZA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "color-name-2.1.0" = {
      name = "color-name";
      packageName = "color-name";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-2.1.0.tgz";
        sha512 = "1bPaDNFm0axzE4MEAzKPuqKWeRaT43U/hyxKPBdqTfmPF+d6n7FSoTFxLVULUJOmiLp01KjhIPPH+HrXZJN4Rg==";
      };
    };
    "color-parse-2.0.2" = {
      name = "color-parse";
      packageName = "color-parse";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-parse/-/color-parse-2.0.2.tgz";
        sha512 = "eCtOz5w5ttWIUcaKLiktF+DxZO1R9KLNY/xhbV6CkhM7sR3GhVghmt6X6yOnzeaM24po+Z9/S1apbXMwA3Iepw==";
      };
    };
    "color-rgba-3.0.0" = {
      name = "color-rgba";
      packageName = "color-rgba";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-rgba/-/color-rgba-3.0.0.tgz";
        sha512 = "PPwZYkEY3M2THEHHV6Y95sGUie77S7X8v+h1r6LSAPF3/LL2xJ8duUXSrkic31Nzc4odPwHgUbiX/XuTYzQHQg==";
      };
    };
    "color-space-2.3.2" = {
      name = "color-space";
      packageName = "color-space";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-space/-/color-space-2.3.2.tgz";
        sha512 = "BcKnbOEsOarCwyoLstcoEztwT0IJxqqQkNwDuA3a65sICvvHL2yoeV13psoDFh5IuiOMnIOKdQDwB4Mk3BypiA==";
      };
    };
    "cronstrue-2.59.0" = {
      name = "cronstrue";
      packageName = "cronstrue";
      version = "2.59.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cronstrue/-/cronstrue-2.59.0.tgz";
        sha512 = "YKGmAy84hKH+hHIIER07VCAHf9u0Ldelx1uU6EBxsRPDXIA1m5fsKmJfyC3xBhw6cVC/1i83VdbL4PvepTrt8A==";
      };
    };
    "debug-4.4.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
        sha512 = "RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
      };
    };
    "dedent-js-1.0.1" = {
      name = "dedent-js";
      packageName = "dedent-js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dedent-js/-/dedent-js-1.0.1.tgz";
        sha512 = "OUepMozQULMLUmhxS95Vudo0jb0UchLimi3+pQ2plj61Fcy8axbP9hbiD4Sz6DPqn6XG3kfmziVfQ1rSys5AJQ==";
      };
    };
    "defu-6.1.4" = {
      name = "defu";
      packageName = "defu";
      version = "6.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/defu/-/defu-6.1.4.tgz";
        sha512 = "mEQCMmwJu317oSz8CwdIOdwf3xMif1ttiM8LTufzc3g6kR+9Pe236twL8j3IYT1F7GfRgGcW6MWxzZjLIkuHIg==";
      };
    };
    "deprecation-2.3.1" = {
      name = "deprecation";
      packageName = "deprecation";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deprecation/-/deprecation-2.3.1.tgz";
        sha512 = "xmHIy4F3scKVwMsQ4WnVaS8bHOx0DmVwRywosKhaILI0ywMDWPtBSku2HNxRvF7jtwDRsoEwYQSfbxj8b7RlJQ==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "error-ex-1.3.4" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.4.tgz";
        sha512 = "sqQamAnR14VgCr1A618A3sGrygcpK+HEbenA/HiEAkkUwcZIIB/tgWqHFxWgOyDh4nB4JCRimh79dR5Ywc9MDQ==";
      };
    };
    "esm-env-1.2.2" = {
      name = "esm-env";
      packageName = "esm-env";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esm-env/-/esm-env-1.2.2.tgz";
        sha512 = "Epxrv+Nr/CaL4ZcFGPJIYLWFom+YeV1DqMLHJoEd9SYRxNbaFruBwfEX/kkHUJf55j2+TUbmDcmuilbP1TmXHA==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "esrap-2.1.3" = {
      name = "esrap";
      packageName = "esrap";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrap/-/esrap-2.1.3.tgz";
        sha512 = "T/Dhhv/QH+yYmiaLz9SA3PW+YyenlnRKDNdtlYJrSOBmNsH4nvPux+mTwx7p+wAedlJrGoZtXNI0a0MjQ2QkVg==";
      };
    };
    "fast-content-type-parse-2.0.1" = {
      name = "fast-content-type-parse";
      packageName = "fast-content-type-parse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-content-type-parse/-/fast-content-type-parse-2.0.1.tgz";
        sha512 = "nGqtvLrj5w0naR6tDPfB4cUmYCqouzyQiz6C5y/LtcDllJdrcc6WaWW6iXyIIOErTa/XRybj28aasdn4LkVk6Q==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-glob-3.3.3" = {
      name = "fast-glob";
      packageName = "fast-glob";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.3.3.tgz";
        sha512 = "7MptL8U0cqcFdzIzwOTHoilX9x5BrNqye7Z/LuC7kCMRio1EMSyqRK3BEAUD7sXRq4iT4AzTVuZdhgQ2TCvYLg==";
      };
    };
    "fast-uri-3.1.0" = {
      name = "fast-uri";
      packageName = "fast-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-uri/-/fast-uri-3.1.0.tgz";
        sha512 = "iPeeDKJSWf4IEOasVVrknXpaBV0IApz/gp7S2bb7Z4Lljbl2MGJRqInZiUrQwV16cpzw/D3S5j5Julj/gT52AA==";
      };
    };
    "fastq-1.19.1" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.19.1.tgz";
        sha512 = "GwLTyxkCXjXbxqIhTsMI2Nui8huMPtnxg7krajPJAjnEG/iiOS7i+zCtWGZR9G0NBKbXKh6X9m9UIsYX/N6vvQ==";
      };
    };
    "fill-range-7.1.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
        sha512 = "YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
      };
    };
    "fzf-0.5.2" = {
      name = "fzf";
      packageName = "fzf";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fzf/-/fzf-0.5.2.tgz";
        sha512 = "Tt4kuxLXFKHy8KT40zwsUPUkg1CrsgY25FxA2U/j/0WgEDCk3ddc/zLTCCcbSHX9FcKtLuVaDGtGE/STWC+j3Q==";
      };
    };
    "gh-actions-language-server-0.0.3" = {
      name = "gh-actions-language-server";
      packageName = "gh-actions-language-server";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/gh-actions-language-server/-/gh-actions-language-server-0.0.3.tgz";
        sha512 = "T2ph7OoS0tnpWsxpvdiC5k9rrv5t7BMwZRJANrk4gZzvTZ1/rY1kpJQjVaiYeTrlj2fDgQh5fMwPqkxNaKIGdw==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "globby-14.1.0" = {
      name = "globby";
      packageName = "globby";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-14.1.0.tgz";
        sha512 = "0Ia46fDOaT7k4og1PDW4YbodWWr3scS2vAr2lTbsplOt2WkKp0vQbkI9wKis/T5LV/dqPjO3bpS/z6GTJB82LA==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hosted-git-info-7.0.2" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-7.0.2.tgz";
        sha512 = "puUZAUKT5m8Zzvs72XWy3HtvVbTWljRE66cP60bxJzAqf2DgICo7lYTY2IHUmLnNpjYvw5bvmoHvPc0QO2a62w==";
      };
    };
    "ignore-7.0.5" = {
      name = "ignore";
      packageName = "ignore";
      version = "7.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-7.0.5.tgz";
        sha512 = "Hs59xBNfUIunMFgWAbGX5cq6893IbWg4KnrjbYwX3tx0ztorVgTDA6B2sxf8ejHJ4wz8BqGUMYlnzNBer5NvGg==";
      };
    };
    "indent-string-4.0.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-4.0.0.tgz";
        sha512 = "EdDDZu4A2OyIK7Lr/2zG+w5jmbuk1DVBnEwREQvBzspBJkCEbRa8GxU1lghYcaGJCnRWibjDXlq779X1/y5xwg==";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha512 = "zz06S8t0ozoDXMG+ube26zeCTNXcKIPJZJi8hBrF4idCLms4CG9QtK7qBl1boi5ODzFpjswb5JPmHCbMpjaYzg==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-plain-object-5.0.0" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-5.0.0.tgz";
        sha512 = "VRSzKkbMm5jMDoKLbltAkFQ5Qr7VDiTFGXxYFXXowVj387GeGNOCsOH6Msy00SGZ3Fp84b1Naa1psqgcCIEP5Q==";
      };
    };
    "is-reference-3.0.3" = {
      name = "is-reference";
      packageName = "is-reference";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-reference/-/is-reference-3.0.3.tgz";
        sha512 = "ixkJoqQvAP88E6wLydLGGqCJsrFUnqoH6HnaczB8XmDH1oaWU+xxdptvikTgaEhtZ53Ky6YXiBuUI2WXLMCwjw==";
      };
    };
    "istextorbinary-6.0.0" = {
      name = "istextorbinary";
      packageName = "istextorbinary";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/istextorbinary/-/istextorbinary-6.0.0.tgz";
        sha512 = "4j3UqQCa06GAf6QHlN3giz2EeFU7qc6Q5uB/aY7Gmb3xmLDLepDOtsZqkb4sCfJgFvTbLUinNw0kHgHs8XOHoQ==";
      };
    };
    "jiti-2.6.1" = {
      name = "jiti";
      packageName = "jiti";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-2.6.1.tgz";
        sha512 = "ekilCSN1jwRvIbgeg/57YFh8qQDNbwDb9xT/qu2DAHbFFZUicIl4ygVaAvzveMhMVr3LnpSKTNnwt8PoOfmKhQ==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "js-yaml-3.14.2" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.2.tgz";
        sha512 = "PMSmkqxr106Xa156c2M265Z+FTrPl+oxd/rgOQy2tijQeK5TxQ43psO1ZCwhVOSdnn+RzkzlRz/eY4BgJBYVpg==";
      };
    };
    "js-yaml-4.1.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.1.tgz";
        sha512 = "qQKT4zQxXl8lLwBtHMWwaTcGfFOZviOJet3Oy/xmGk2gZH677CJM9EvtfdSkgWcATZhj/55JZ0rmy3myCT5lsA==";
      };
    };
    "json-parse-even-better-errors-3.0.2" = {
      name = "json-parse-even-better-errors";
      packageName = "json-parse-even-better-errors";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-even-better-errors/-/json-parse-even-better-errors-3.0.2.tgz";
        sha512 = "fi0NG4bPjCHunUJffmLd0gxssIgkNmArMvis4iNah6Owg1MCJjWhEcDLmsK6iGkJq3tHwbDkTlce70/tmXN4cQ==";
      };
    };
    "json-schema-traverse-1.0.0" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
        sha512 = "NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
      };
    };
    "json5-2.2.3" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.3.tgz";
        sha512 = "XmOWe7eyHYH14cLdVPoyg+GOH3rYX++KpzrylJwSW98t3Nk+U8XOl8FWKOgwtzdb8lXGf6zYwDUzeHMWfxasyg==";
      };
    };
    "lines-and-columns-2.0.4" = {
      name = "lines-and-columns";
      packageName = "lines-and-columns";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-2.0.4.tgz";
        sha512 = "wM1+Z03eypVAVUCE7QdSqpVIvelbOakn1M0bPDoA4SGWPx3sNDVUiMo3L6To6WWGClB7VyXnhQ4Sn7gxiJbE6A==";
      };
    };
    "locate-character-3.0.0" = {
      name = "locate-character";
      packageName = "locate-character";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-character/-/locate-character-3.0.0.tgz";
        sha512 = "SW13ws7BjaeJ6p7Q6CO2nchbYEc3X3J6WrmTTDto7yMPqVSZTUyY5Tjbid+Ab8gLnATtygYtiDIJGQRRn2ZOiA==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash.truncate-4.4.2" = {
      name = "lodash.truncate";
      packageName = "lodash.truncate";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.truncate/-/lodash.truncate-4.4.2.tgz";
        sha512 = "jttmRe7bRse52OsWIMDLaXxWqRAmtIUccAQ3garviCqJjafXOfNMO0yMfNpdD6zbGaTU0P5Nz7e7gAT6cKmJRw==";
      };
    };
    "lru-cache-10.4.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.4.3.tgz";
        sha512 = "JNAzZcXrCt42VGLuYz0zfAzDfAvJWW6AfYlDBQyDV5DClI2m5sAmK+OIO7s59XfsRsWHp02jAJrRadPRGTt6SQ==";
      };
    };
    "lru-cache-11.2.2" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "11.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-11.2.2.tgz";
        sha512 = "F9ODfyqML2coTIsQpSkRHnLSZMtkU8Q+mSfcaIyKwy58u+8k5nvAYeiNhsyMARvzNcXJ9QfWVrcPsC9e9rAxtg==";
      };
    };
    "magic-string-0.30.21" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.21.tgz";
        sha512 = "vd2F4YUyEXKGcLHoq+TEyCjxueSeHnFxyyjNp80yg0XV4vUhnDer/lvvlqM/arB5bXQN5K2/3oinyCRyx8T2CQ==";
      };
    };
    "meow-12.1.1" = {
      name = "meow";
      packageName = "meow";
      version = "12.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/meow/-/meow-12.1.1.tgz";
        sha512 = "BhXM0Au22RwUneMPwSCnyhTOizdWoIEPU9sp0Aqa1PnDMR5Wv2FGXYDjuzJEIX+Eo2Rb8xuYe5jrnm5QowQFkw==";
      };
    };
    "merge2-1.4.1" = {
      name = "merge2";
      packageName = "merge2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
        sha512 = "8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
      };
    };
    "micromatch-4.0.8" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.8.tgz";
        sha512 = "PXwfBhYu0hBCPw8Dn0E+WDYb7af3dSLVWKi3HGv84IdF4TyFoC0ysxFd0Goxw7nSv4T/PzEJQxsYsEiFCKo2BA==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "node-fetch-2.7.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.7.0.tgz";
        sha512 = "c4FRfUm/dbcWZ7U+1Wq0AwCyFL+3nt2bEw05wfxSz+DWpWsitgmSgYmy2dQdWyKC1694ELPqMs/YzUSNozLt8A==";
      };
    };
    "normalize-package-data-6.0.2" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-6.0.2.tgz";
        sha512 = "V6gygoYb/5EmNI+MEGrWkC+e6+Rr7mTmfHrxDbLzxQogBkgzo76rkok0Am6thgSF7Mv2nLOajAJj5vDJZEFn7g==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "p-map-4.0.0" = {
      name = "p-map";
      packageName = "p-map";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-map/-/p-map-4.0.0.tgz";
        sha512 = "/bjOqmgETBYB5BoEeGVea8dmvHb2m9GLy1E9W43yeyfP6QQCZGFNa+XRceJEuDB6zqr+gKpIAmlLebMpykw/MQ==";
      };
    };
    "parse-json-7.1.1" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-7.1.1.tgz";
        sha512 = "SgOTCX/EZXtZxBE5eJ97P4yGM5n37BwRU+YMsH4vNzFqJV/oWFXXCmwFlgWUM4PrakybVOueJJ6pwHqSVhTFDw==";
      };
    };
    "path-type-6.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-6.0.0.tgz";
        sha512 = "Vj7sf++t5pBD637NSfkxpHSMfWaeig5+DKWLhcqIYx6mWQz5hdJTGDVMQiJcw1ZYkhs7AazKDGpRVji1LJCZUQ==";
      };
    };
    "picocolors-1.1.1" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
        sha512 = "xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pluralize-2.0.0" = {
      name = "pluralize";
      packageName = "pluralize";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pluralize/-/pluralize-2.0.0.tgz";
        sha512 = "TqNZzQCD4S42De9IfnnBvILN7HAW7riLqsCyp8lgjXeysyPlX5HhqKAcJHHHb9XskE4/a+7VGC9zzx8Ls0jOAw==";
      };
    };
    "pluralize-8.0.0" = {
      name = "pluralize";
      packageName = "pluralize";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pluralize/-/pluralize-8.0.0.tgz";
        sha512 = "Nc3IT5yHzflTfbjgqWcCPpo7DaKy4FnpB0l/zCAW0Tc7jxAiuqSxHasntB3D7887LSrA93kDJ9IXovxJYxyLCA==";
      };
    };
    "quansync-0.2.11" = {
      name = "quansync";
      packageName = "quansync";
      version = "0.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/quansync/-/quansync-0.2.11.tgz";
        sha512 = "AifT7QEbW9Nri4tAwR5M/uzpBuqfZf+zwaEM/QkzEjj7NBuFD2rBuy0K3dE+8wltbezDV7JMA0WfnCPYRSYbXA==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "rc-config-loader-4.1.3" = {
      name = "rc-config-loader";
      packageName = "rc-config-loader";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc-config-loader/-/rc-config-loader-4.1.3.tgz";
        sha512 = "kD7FqML7l800i6pS6pvLyIE2ncbk9Du8Q0gp/4hMPhJU6ZxApkoLcGD8ZeqgiAlfwZ6BlETq6qqe+12DUL207w==";
      };
    };
    "read-pkg-8.1.0" = {
      name = "read-pkg";
      packageName = "read-pkg";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-pkg/-/read-pkg-8.1.0.tgz";
        sha512 = "PORM8AgzXeskHO/WEv312k9U03B8K9JSiWF/8N9sUuFjBa+9SF2u6K7VClzXwDXab51jCd8Nd36CNM+zR97ScQ==";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "reusify-1.1.0" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.1.0.tgz";
        sha512 = "g6QUff04oZpHs0eG5p83rFLhHeV00ug/Yf9nZM6fLeUrPguBTkTQOdpAWWspMh55TZfVQDPaN3NQJfbVRAxdIw==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "scule-1.3.0" = {
      name = "scule";
      packageName = "scule";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scule/-/scule-1.3.0.tgz";
        sha512 = "6FtHJEvt+pVMIB9IBY+IcCJ6Z5f1iQnytgyfKMhDKgmzYG+TeH/wx1y3l27rshSbLiSanrR9ffZDrEsmjlQF2g==";
      };
    };
    "secretlint-8.5.0" = {
      name = "secretlint";
      packageName = "secretlint";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/secretlint/-/secretlint-8.5.0.tgz";
        sha512 = "b/X+uHWNbrHZBcPmfHyYGFeNUGOycvFboBmV/zqo7Rti7fnLhYllcSi8WvsRROki7bFFoslEbcqPYnTzJF4k6Q==";
      };
    };
    "semver-7.7.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz";
        sha512 = "SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
      };
    };
    "slash-5.1.0" = {
      name = "slash";
      packageName = "slash";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slash/-/slash-5.1.0.tgz";
        sha512 = "ZA6oR3T/pEyuqwMgAKT0/hAv8oAXckzbkmR0UkUosQ+Mc4RxGoJkRmwHgHufaenlyAgE1Mxgpdcrf75y6XcnDg==";
      };
    };
    "slice-ansi-4.0.0" = {
      name = "slice-ansi";
      packageName = "slice-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slice-ansi/-/slice-ansi-4.0.0.tgz";
        sha512 = "qMCMfhY040cVHT43K9BFygqYbUPFZKHOg7K73mtTWJRb8pyP3fzf4Ixd5SzdEJQ6MRUg/WBnOLxghZtKKurENQ==";
      };
    };
    "spdx-correct-3.2.0" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-3.2.0.tgz";
        sha512 = "kN9dJbvnySHULIluDHy32WHRUu3Og7B9sbY7tsFLctQkIqnMh3hErYgdMjTYuqmcXX+lK5T1lnUt3G7zNswmZA==";
      };
    };
    "spdx-exceptions-2.5.0" = {
      name = "spdx-exceptions";
      packageName = "spdx-exceptions";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-exceptions/-/spdx-exceptions-2.5.0.tgz";
        sha512 = "PiU42r+xO4UbUS1buo3LPJkjlO7430Xn5SVAhdpzzsPHsjbYVflnnFdATgabnLude+Cqu25p6N+g2lw/PFsa4w==";
      };
    };
    "spdx-expression-parse-3.0.1" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-3.0.1.tgz";
        sha512 = "cbqHunsQWnJNE6KhVSMsMeH5H/L9EpymbzqTQ3uLwNCLZ1Q481oWaofqH7nO6V07xlXwY6PhQdQ2IedWx/ZK4Q==";
      };
    };
    "spdx-license-ids-3.0.22" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "3.0.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-3.0.22.tgz";
        sha512 = "4PRT4nh1EImPbt2jASOKHX7PB7I+e4IWNLvkKFDxNhJlfjbYlleYQh285Z/3mPTHSAK/AvdMmw5BNNuYH8ShgQ==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha512 = "D9cPgkvLlV3t3IzL0D0YLvGA9Ahk4PcvVwUbN0dSGr1aP0Nrt4AEnTUbuGvquEC0mA64Gqt1fzirlRs5ibXx8g==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "structured-source-4.0.0" = {
      name = "structured-source";
      packageName = "structured-source";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/structured-source/-/structured-source-4.0.0.tgz";
        sha512 = "qGzRFNJDjFieQkl/sVOI2dUjHKRyL9dAJi2gCPGJLbJHBIkyOHxjuocpIEfbLioX+qSJpvbYdT49/YCdMznKxA==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "supports-hyperlinks-2.3.0" = {
      name = "supports-hyperlinks";
      packageName = "supports-hyperlinks";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-hyperlinks/-/supports-hyperlinks-2.3.0.tgz";
        sha512 = "RpsAZlpWcDwOPQA22aCH4J0t7L8JmAvsCxfOSEwm7cQs3LshN36QaTkwd70DnBOXDWGssw2eUoc8CaRWT0XunA==";
      };
    };
    "svelte-5.43.14" = {
      name = "svelte";
      packageName = "svelte";
      version = "5.43.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-5.43.14.tgz";
        sha512 = "pHeUrp1A5S6RGaXhJB7PtYjL1VVjbVrJ2EfuAoPu9/1LeoMaJa/pcdCsCSb0gS4eUHAHnhCbUDxORZyvGK6kOQ==";
      };
    };
    "svelte2tsx-0.7.45" = {
      name = "svelte2tsx";
      packageName = "svelte2tsx";
      version = "0.7.45";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte2tsx/-/svelte2tsx-0.7.45.tgz";
        sha512 = "cSci+mYGygYBHIZLHlm/jYlEc1acjAHqaQaDFHdEBpUueM9kSTnPpvPtSl5VkJOU1qSJ7h1K+6F/LIUYiqC8VA==";
      };
    };
    "table-6.9.0" = {
      name = "table";
      packageName = "table";
      version = "6.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/table/-/table-6.9.0.tgz";
        sha512 = "9kY+CygyYM6j02t5YFHbNz2FN5QmYGv9zAjVp4lCDjlCw7amdckXlEt/bjMhUIfj4ThGRE4gCUH5+yGnNuPo5A==";
      };
    };
    "terminal-link-2.1.1" = {
      name = "terminal-link";
      packageName = "terminal-link";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/terminal-link/-/terminal-link-2.1.1.tgz";
        sha512 = "un0FmiRUQNr5PJqy9kP7c40F5BOfpGlYTrxonDChEZB7pzZxRNp/bt+ymiy9/npwXya9KH99nJ/GXFIiUkYGFQ==";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha512 = "N+8UisAXDGk8PFXP4HAzVR9nbfmVJ3zYLAWiTIoqC5v5isinhr+r5uaO8+7r3BMfuNIufIsA7RdpVgacC2cSpw==";
      };
    };
    "textextensions-5.16.0" = {
      name = "textextensions";
      packageName = "textextensions";
      version = "5.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/textextensions/-/textextensions-5.16.0.tgz";
        sha512 = "7D/r3s6uPZyU//MCYrX6I14nzauDwJ5CxazouuRGNuvSCihW87ufN6VLoROLCrHg6FblLuJrT6N2BVaPVzqElw==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha512 = "N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==";
      };
    };
    "try-resolve-1.0.1" = {
      name = "try-resolve";
      packageName = "try-resolve";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/try-resolve/-/try-resolve-1.0.1.tgz";
        sha512 = "yHeaPjCBzVaXwWl5IMUapTaTC2rn/eBYg2fsG2L+CvJd+ttFbk0ylDnpTO3wVhosmE1tQEvcebbBeKLCwScQSQ==";
      };
    };
    "type-fest-0.21.3" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.21.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.21.3.tgz";
        sha512 = "t0rzBq87m3fVcduHDUFhKmyyX+9eo6WQjZvf51Ea/M0Q7+T374Jp1aUiyUl0GKxp8M/OETVHSDvmkyPgvX+X2w==";
      };
    };
    "type-fest-3.13.1" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "3.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-3.13.1.tgz";
        sha512 = "tLq3bSNx+xSpwvAJnzrK0Ep5CLNWjvFTOp71URMaAEWBfRb9nnJiBoUe0tF8bI4ZFO3omgBR6NvnbzVUT3Ly4g==";
      };
    };
    "type-fest-4.41.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "4.41.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-4.41.0.tgz";
        sha512 = "TeTSQ6H5YHvpqVwBRcnLDCBnDOHWYu7IvGbHT6N8AOymcr9PJGjc1GTtiWZTYg0NCgYwvnYWEkVChQAr9bjfwA==";
      };
    };
    "typescript-5.9.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
        sha512 = "jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
      };
    };
    "typescript-svelte-plugin-0.3.50" = {
      name = "typescript-svelte-plugin";
      packageName = "typescript-svelte-plugin";
      version = "0.3.50";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-svelte-plugin/-/typescript-svelte-plugin-0.3.50.tgz";
        sha512 = "CD6jMNAYJwqCyQ5zZBDRuveeJvAgIogLwXMf5eXAl4K36wD8W+Npw49h6j5fXnpd7SKcG3uptGpeCGETED6WSA==";
      };
    };
    "unconfig-7.4.1" = {
      name = "unconfig";
      packageName = "unconfig";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unconfig/-/unconfig-7.4.1.tgz";
        sha512 = "uyQ7LElcGizrOGZyIq9KU+xkuEjcRf9IpmDTkCSYv5mEeZzrXSj6rb51C0L+WTedsmAoVxW9WKrLWhSwebIM9Q==";
      };
    };
    "unconfig-core-7.4.1" = {
      name = "unconfig-core";
      packageName = "unconfig-core";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unconfig-core/-/unconfig-core-7.4.1.tgz";
        sha512 = "Bp/bPZjV2Vl/fofoA2OYLSnw1Z0MOhCX7zHnVCYrazpfZvseBbGhwcNQMxsg185Mqh7VZQqK3C8hFG/Dyng+yA==";
      };
    };
    "unicorn-magic-0.3.0" = {
      name = "unicorn-magic";
      packageName = "unicorn-magic";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unicorn-magic/-/unicorn-magic-0.3.0.tgz";
        sha512 = "+QBBXBCvifc56fsbuxZQ6Sic3wqqc3WWaqxs58gvJrcOuN83HGTCwz3oS5phzU9LthRNE9VrJCFCLUgHeeFnfA==";
      };
    };
    "universal-user-agent-6.0.1" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-6.0.1.tgz";
        sha512 = "yCzhz6FN2wU1NiiQRogkTQszlQSlpWaw8SvVegAc+bDxbzHgh1vX8uIe8OYyMH6DwH+sdTJsgMl36+mSMdRJIQ==";
      };
    };
    "universal-user-agent-7.0.3" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-7.0.3.tgz";
        sha512 = "TmnEAEAsBJVZM/AADELsK76llnwcf9vMKuPz8JflO1frO8Lchitr0fNaN9d+Ap0BjKtqWqd/J17qeDnXh8CL2A==";
      };
    };
    "unocss-language-server-0.1.8" = {
      name = "unocss-language-server";
      packageName = "unocss-language-server";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/unocss-language-server/-/unocss-language-server-0.1.8.tgz";
        sha512 = "PL9OqWQx3ehXZmOYEwZ42ZWXlC23M3VEDxJWuk4k1Z8FnFkiwm8ox7/NuctxqbLXtkmUouDRqEeZU27a2NZRGw==";
      };
    };
    "validate-npm-package-license-3.0.4" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.4.tgz";
        sha512 = "DpKm2Ui/xN7/HQKCtpZxoRWBhZ9Z0kqtygG8XCgNQ8ZlDnxuQmWhj566j8fN4Cu3/JmbhsDo7fcAJq4s9h27Ew==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-jsonrpc-8.2.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz";
        sha512 = "C+r0eKJUIfiDIfwJhria30+TYWPtuHJXHtI7J0YlOmKAo7ogxP20T0zxB7HZQIFhIyvoBPwWskjxrvAtfjyZfA==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-9.0.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-9.0.1.tgz";
        sha512 = "woByF3PDpkHFUreUa7Hos7+pUWdeWMXRd26+ZX2A8cFx6v/JPTtd4/uN0/jB6XQHYaOlHbio03NTHCqrgG5n7g==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-protocol-3.17.5" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz";
        sha512 = "mb1bvRJN8SVznADSGWM9u/b07H7Ecg0I3OgXDuLdn307rl/J3A9YD6/eYOssqhecL27hK1IPZAsaqh00i/Jljg==";
      };
    };
    "vscode-languageserver-textdocument-1.0.12" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.12.tgz";
        sha512 = "cxWNPesCnQCcMPeenjKKsOCKQZ/L6Tv19DTRIGuLWe32lyzWhihGVJ/rcckZXJxfdKCFvRLS3fpBIsV/ZGX4zA==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha512 = "2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha512 = "saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yaml-2.8.1" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.8.1.tgz";
        sha512 = "lcYcMxX2PO9XMGvAJkJ3OsNMw+/7FKes7/hgerGUYWIoWu5j/+YQqcZr5JnPZWzOsEBgMbSbiSTn/dv/69Mkpw==";
      };
    };
    "zimmerframe-1.1.4" = {
      name = "zimmerframe";
      packageName = "zimmerframe";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/zimmerframe/-/zimmerframe-1.1.4.tgz";
        sha512 = "B58NGBEoc8Y9MWWCQGl/gq9xBCe4IiKM0a2x7GZdQKOW5Exr8S1W24J6OgM1njK8xCRGvAJIL/MxXHf6SkmQKQ==";
      };
    };
  };
  args = {
    name = "node_servers";
    packageName = "node_servers";
    src = ./.;
    dependencies = [
      sources."@actions/expressions-0.3.20"
      (
        sources."@actions/languageserver-0.3.20"
        // {
          dependencies = [
            sources."@octokit/auth-token-5.1.2"
            (
              sources."@octokit/core-6.1.6"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            (
              sources."@octokit/endpoint-10.1.4"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            (
              sources."@octokit/graphql-8.2.2"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            sources."@octokit/openapi-types-25.1.0"
            (
              sources."@octokit/plugin-paginate-rest-11.6.0"
              // {
                dependencies = [
                  sources."@octokit/openapi-types-24.2.0"
                  sources."@octokit/types-13.10.0"
                ];
              }
            )
            sources."@octokit/plugin-request-log-5.3.1"
            (
              sources."@octokit/plugin-rest-endpoint-methods-13.5.0"
              // {
                dependencies = [
                  sources."@octokit/openapi-types-24.2.0"
                  sources."@octokit/types-13.10.0"
                ];
              }
            )
            (
              sources."@octokit/request-9.2.4"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            (
              sources."@octokit/request-error-6.1.8"
              // {
                dependencies = [
                  sources."@octokit/types-14.1.0"
                ];
              }
            )
            sources."@octokit/rest-21.1.1"
            sources."before-after-hook-3.0.2"
            sources."universal-user-agent-7.0.3"
          ];
        }
      )
      sources."@actions/languageservice-0.3.20"
      sources."@actions/workflow-parser-0.3.20"
      sources."@azu/format-text-1.0.2"
      sources."@azu/style-format-1.0.1"
      sources."@babel/code-frame-7.27.1"
      sources."@babel/helper-validator-identifier-7.28.5"
      sources."@jridgewell/gen-mapping-0.3.13"
      sources."@jridgewell/remapping-2.3.5"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/sourcemap-codec-1.5.5"
      sources."@jridgewell/trace-mapping-0.3.31"
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.8"
      sources."@octokit/auth-token-3.0.4"
      sources."@octokit/core-4.2.4"
      sources."@octokit/endpoint-7.0.6"
      sources."@octokit/graphql-5.0.6"
      sources."@octokit/openapi-types-18.1.1"
      sources."@octokit/plugin-paginate-rest-6.1.2"
      sources."@octokit/plugin-request-log-1.0.4"
      (
        sources."@octokit/plugin-rest-endpoint-methods-7.2.3"
        // {
          dependencies = [
            sources."@octokit/types-10.0.0"
          ];
        }
      )
      sources."@octokit/request-6.2.8"
      sources."@octokit/request-error-3.0.3"
      sources."@octokit/rest-19.0.13"
      sources."@octokit/tsconfig-1.0.2"
      sources."@octokit/types-9.3.2"
      sources."@quansync/fs-0.1.5"
      sources."@secretlint/config-creator-8.5.0"
      sources."@secretlint/config-loader-8.5.0"
      sources."@secretlint/core-8.5.0"
      sources."@secretlint/formatter-8.5.0"
      sources."@secretlint/node-8.5.0"
      sources."@secretlint/profiler-8.5.0"
      sources."@secretlint/resolver-8.5.0"
      sources."@secretlint/secretlint-rule-preset-recommend-8.5.0"
      sources."@secretlint/source-creator-8.5.0"
      sources."@secretlint/types-8.5.0"
      sources."@sindresorhus/merge-streams-2.3.0"
      sources."@sveltejs/acorn-typescript-1.0.7"
      sources."@textlint/ast-node-types-14.8.4"
      (
        sources."@textlint/linter-formatter-14.8.4"
        // {
          dependencies = [
            sources."pluralize-2.0.0"
          ];
        }
      )
      sources."@textlint/module-interop-14.8.4"
      sources."@textlint/resolver-14.8.4"
      sources."@textlint/types-14.8.4"
      sources."@types/estree-1.0.8"
      sources."@types/normalize-package-data-2.4.4"
      (
        sources."@unocss/autocomplete-66.5.9"
        // {
          dependencies = [
            sources."lru-cache-11.2.2"
          ];
        }
      )
      sources."@unocss/config-66.5.9"
      sources."@unocss/core-66.5.9"
      sources."@unocss/extractor-arbitrary-variants-66.5.9"
      sources."@unocss/preset-mini-66.5.9"
      sources."@unocss/preset-wind3-66.5.9"
      sources."@unocss/rule-utils-66.5.9"
      sources."acorn-8.15.0"
      sources."aggregate-error-3.1.0"
      sources."ajv-8.17.1"
      (
        sources."ansi-escapes-4.3.2"
        // {
          dependencies = [
            sources."type-fest-0.21.3"
          ];
        }
      )
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."argparse-1.0.10"
      sources."aria-query-5.3.2"
      sources."astral-regex-2.0.0"
      sources."axobject-query-4.1.0"
      sources."before-after-hook-2.2.3"
      sources."binaryextensions-4.19.0"
      sources."boundary-2.0.0"
      sources."braces-3.0.3"
      sources."chalk-4.1.2"
      sources."clean-stack-2.2.0"
      sources."clsx-2.1.1"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      (
        sources."color-parse-2.0.2"
        // {
          dependencies = [
            sources."color-name-2.1.0"
          ];
        }
      )
      sources."color-rgba-3.0.0"
      sources."color-space-2.3.2"
      sources."cronstrue-2.59.0"
      sources."debug-4.4.3"
      sources."dedent-js-1.0.1"
      sources."defu-6.1.4"
      sources."deprecation-2.3.1"
      sources."emoji-regex-8.0.0"
      sources."error-ex-1.3.4"
      sources."esm-env-1.2.2"
      sources."esprima-4.0.1"
      sources."esrap-2.1.3"
      sources."fast-content-type-parse-2.0.1"
      sources."fast-deep-equal-3.1.3"
      sources."fast-glob-3.3.3"
      sources."fast-uri-3.1.0"
      sources."fastq-1.19.1"
      sources."fill-range-7.1.1"
      sources."fzf-0.5.2"
      sources."gh-actions-language-server-0.0.3"
      sources."glob-parent-5.1.2"
      sources."globby-14.1.0"
      sources."has-flag-4.0.0"
      sources."hosted-git-info-7.0.2"
      sources."ignore-7.0.5"
      sources."indent-string-4.0.0"
      sources."is-arrayish-0.2.1"
      sources."is-extglob-2.1.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."is-plain-object-5.0.0"
      sources."is-reference-3.0.3"
      sources."istextorbinary-6.0.0"
      sources."jiti-2.6.1"
      sources."js-tokens-4.0.0"
      sources."js-yaml-3.14.2"
      sources."json-parse-even-better-errors-3.0.2"
      sources."json-schema-traverse-1.0.0"
      sources."json5-2.2.3"
      sources."lines-and-columns-2.0.4"
      sources."locate-character-3.0.0"
      sources."lodash-4.17.21"
      sources."lodash.truncate-4.4.2"
      sources."lru-cache-10.4.3"
      sources."magic-string-0.30.21"
      sources."meow-12.1.1"
      sources."merge2-1.4.1"
      sources."micromatch-4.0.8"
      sources."ms-2.1.3"
      sources."node-fetch-2.7.0"
      sources."normalize-package-data-6.0.2"
      sources."once-1.4.0"
      sources."p-map-4.0.0"
      (
        sources."parse-json-7.1.1"
        // {
          dependencies = [
            sources."type-fest-3.13.1"
          ];
        }
      )
      sources."path-type-6.0.0"
      sources."picocolors-1.1.1"
      sources."picomatch-2.3.1"
      sources."pluralize-8.0.0"
      sources."quansync-0.2.11"
      sources."queue-microtask-1.2.3"
      (
        sources."rc-config-loader-4.1.3"
        // {
          dependencies = [
            sources."argparse-2.0.1"
            sources."js-yaml-4.1.1"
          ];
        }
      )
      sources."read-pkg-8.1.0"
      sources."require-from-string-2.0.2"
      sources."reusify-1.1.0"
      sources."run-parallel-1.2.0"
      sources."scule-1.3.0"
      sources."secretlint-8.5.0"
      sources."semver-7.7.3"
      sources."slash-5.1.0"
      sources."slice-ansi-4.0.0"
      sources."spdx-correct-3.2.0"
      sources."spdx-exceptions-2.5.0"
      sources."spdx-expression-parse-3.0.1"
      sources."spdx-license-ids-3.0.22"
      sources."sprintf-js-1.0.3"
      sources."string-width-4.2.3"
      sources."strip-ansi-6.0.1"
      sources."structured-source-4.0.0"
      sources."supports-color-7.2.0"
      sources."supports-hyperlinks-2.3.0"
      sources."svelte-5.43.14"
      sources."svelte2tsx-0.7.45"
      sources."table-6.9.0"
      sources."terminal-link-2.1.1"
      sources."text-table-0.2.0"
      sources."textextensions-5.16.0"
      sources."to-regex-range-5.0.1"
      sources."tr46-0.0.3"
      sources."try-resolve-1.0.1"
      sources."type-fest-4.41.0"
      sources."typescript-5.9.3"
      sources."typescript-svelte-plugin-0.3.50"
      sources."unconfig-7.4.1"
      sources."unconfig-core-7.4.1"
      sources."unicorn-magic-0.3.0"
      sources."universal-user-agent-6.0.1"
      (
        sources."unocss-language-server-0.1.8"
        // {
          dependencies = [
            sources."vscode-jsonrpc-8.2.0"
            sources."vscode-languageserver-9.0.1"
            sources."vscode-languageserver-protocol-3.17.5"
          ];
        }
      )
      sources."validate-npm-package-license-3.0.4"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      (
        sources."vscode-languageserver-protocol-3.17.3"
        // {
          dependencies = [
            sources."vscode-languageserver-types-3.17.3"
          ];
        }
      )
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-uri-3.1.0"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
      sources."wrappy-1.0.2"
      sources."yaml-2.8.1"
      sources."zimmerframe-1.1.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (
    lib.overrideExisting args {
      src = stdenv.mkDerivation {
        name = args.name + "-package-json";
        src = nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ] args.src;
        dontBuild = true;
        installPhase = "mkdir -p $out; cp -r ./* $out;";
      };
    }
  );
}
