name: 'Setup Git Bot'
description: 'Configure git with bot identity for automated commits'

inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App private key'
    required: true

outputs:
  token:
    description: 'GitHub App token for subsequent steps'
    value: ${{ steps.app-token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@bf559f85448f9380bcfa2899dbdc01eb5b37be3a # v3.0.0-beta.2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - name: Configure git bot identity
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
      run: |
        bot_id=$(gh api "users/${APP_SLUG}[bot]" --jq '.id')
        git config user.name "${APP_SLUG}[bot]"
        git config user.email "${bot_id}+${APP_SLUG}[bot]@users.noreply.github.com"
