{
  pkgs,
  lib,
  dotfilesDir,
  ...
}:
let
  nu = lib.getExe pkgs.nushell;

  hooks = [
    "pre-commit"
    "post-commit"
    "post-checkout"
    "post-merge"
    "post-rewrite"
  ];

  # The hook itself only execs; every decision lives in git-hooks.nu. The
  # interpreter is this flake's nushell by store path, so a hook never has to
  # evaluate the flake to find one. The script path stays relative because git
  # runs hooks from the top of the working tree, which makes a linked worktree
  # run its own copy.
  installHook = name: ''
    cat > "$DOTFILES_DIR/.git/hooks/${name}" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by nix/modules/home/git-hooks.nix
    exec ${nu} ./nix/modules/home/git-hooks.nu ${name} "$@"
    HOOK_EOF
    chmod +x "$DOTFILES_DIR/.git/hooks/${name}"
  '';
in
{
  # Install git hooks via Home Manager activation.
  home.activation.installGitHooks = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    DOTFILES_DIR="${dotfilesDir}"
    if [ -d "$DOTFILES_DIR/.git" ]; then
      echo "Installing git hooks for dotfiles..."
      mkdir -p "$DOTFILES_DIR/.git/hooks"
      ${lib.concatMapStrings installHook hooks}
      echo "Git hooks installed successfully!"
    fi
  '';
}
