{
  lib,
  dotfilesDir,
  ...
}:
{
  # Install git hooks via Home Manager activation
  # Note: pre-commit hook is managed by devShell via git-hooks.nix flakeModule
  # These hooks auto-run `nix run .#switch` when nix config changes
  home.activation.installGitHooks = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        DOTFILES_DIR="${dotfilesDir}"
        if [ -d "$DOTFILES_DIR/.git" ]; then
          echo "Installing git hooks for dotfiles..."
          mkdir -p "$DOTFILES_DIR/.git/hooks"

          # Create the post-commit hook for nix-apply
          cat > "$DOTFILES_DIR/.git/hooks/post-commit" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by modules/home/git-hooks.nix
    # Skip during rebase, merge, or cherry-pick operations
    if [ -d "$(git rev-parse --git-dir)/rebase-merge" ] || \
       [ -d "$(git rev-parse --git-dir)/rebase-apply" ] || \
       [ -f "$(git rev-parse --git-dir)/MERGE_HEAD" ] || \
       [ -f "$(git rev-parse --git-dir)/CHERRY_PICK_HEAD" ]; then
      exit 0
    fi

    if git diff HEAD^..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/|aqua/aqua.yaml)'; then
      echo "Nix configuration changed. Applying changes..."
      nix run .#switch
    fi
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/post-commit"

          # Create the post-checkout hook
          cat > "$DOTFILES_DIR/.git/hooks/post-checkout" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by modules/home/git-hooks.nix
    # post-checkout receives: $1=prev HEAD, $2=new HEAD, $3=flag
    # Skip if just restoring files (flag=0)
    if [ "$3" = "0" ]; then
      exit 0
    fi

    # Skip during rebase operations
    if [ -d "$(git rev-parse --git-dir)/rebase-merge" ] || \
       [ -d "$(git rev-parse --git-dir)/rebase-apply" ]; then
      exit 0
    fi

    if git diff HEAD@{1}..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/|aqua/aqua.yaml)'; then
      echo "Nix configuration changed. Applying changes..."
      nix run .#switch
    fi
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/post-checkout"

          # Create the post-merge hook
          cat > "$DOTFILES_DIR/.git/hooks/post-merge" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by modules/home/git-hooks.nix
    if git diff HEAD@{1}..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/|aqua/aqua.yaml)'; then
      echo "Nix configuration changed. Applying changes..."
      nix run .#switch
    fi
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/post-merge"

          # Create the post-rewrite hook (triggered after git pull --rebase)
          cat > "$DOTFILES_DIR/.git/hooks/post-rewrite" << 'HOOK_EOF'
    #!/usr/bin/env bash
    # Generated by modules/home/git-hooks.nix
    # post-rewrite receives: $1=rebase or amend
    # Only run after rebase (not amend, which is handled by post-commit)
    if [ "$1" != "rebase" ]; then
      exit 0
    fi

    # Compare ORIG_HEAD (before rebase) with HEAD (after rebase)
    if git diff ORIG_HEAD..HEAD --name-only 2>/dev/null | grep -qE '^(flake.nix|flake.lock|nix/|aqua/aqua.yaml)'; then
      echo "Nix configuration changed after rebase. Applying changes..."
      nix run .#switch
    fi
    HOOK_EOF
          chmod +x "$DOTFILES_DIR/.git/hooks/post-rewrite"

          echo "Git hooks installed successfully!"
        fi
  '';
}
