name: 'Environment Setup'
description: 'Setup environment for CI'
inputs:
  aqua_config:
    description: 'Aqua config file path'
    required: false
    default: aqua/aqua.yaml
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Golang
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: 'stable'
    - name: Install aqua
      uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
      with:
        aqua_version: v2.55.1
        policy_allow: "true"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        AQUA_CONFIG: ${{ inputs.aqua_config }}
        AQUA_LOG_COLOR: always

