name: 'Environment Setup'
description: 'Setup environment for CI'
inputs:
  aqua_config:
    description: 'Aqua config file path'
    required: false
    default: aqua/aqua.yaml
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Golang
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: 'stable'
    - name: Install aqua
      uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
      with:
        aqua_version: v2.53.9
        policy_allow: "true"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        AQUA_CONFIG: ${{ inputs.aqua_config }}
        AQUA_LOG_COLOR: always

