name: 'Environment Setup'
description: 'Setup environment for CI'
inputs:
  aqua_config:
    description: 'Aqua config file path'
    required: false
    default: aqua/aqua.yaml
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Golang
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: 'stable'
    - name: Install aqua
      uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
      with:
        aqua_version: v2.45.1
        policy_allow: "true"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        AQUA_CONFIG: ${{ inputs.aqua_config }}
        AQUA_LOG_COLOR: always

