name: 'Environment Setup'
description: 'Setup environment for CI'
inputs:
  aqua_config:
    description: 'Aqua config file path'
    required: false
    default: aqua/aqua.yaml
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Golang
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: 'stable'
    - name: Install aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.51.1
        policy_allow: "true"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        AQUA_CONFIG: ${{ inputs.aqua_config }}
        AQUA_LOG_COLOR: always

