[default]
locale = 'en-gb'
extend-ignore-re = [
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
  "(?s)<!--\\s*spellchecker:off.*?\\n\\s*spellchecker:on\\s*-->",
  "(?Rm)^.*#\\s*spellchecker:disable-line$",
  "(?m)^.*<!--\\s*spellchecker:disable-line\\s*-->\\n.*$",
  "(?s)```.*?``` ", # ignore code blocks
  "(?s)```[a-zA-Z0-9]*\n.*?```", # ignore code blocks
  "(?s)`.*?` ", # ignore inline code
]

[files]
extend-exclude = [ "node_modules/**" ]
