name: 'Setup Nix'
description: 'Install Nix and configure Magic Nix Cache'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
