# This file is generated by nvimx. Do not edit by hand.
{
  inputs = {
    lazy-nvim = {
      url = "github:folke/lazy.nvim/85c7ff3711b730b4030d03144f6db6375044ae82";
      flake = false;
    };
    actions-preview-nvim = {
      url = "github:aznhe21/actions-preview.nvim/0ac9c2aa3cfc8c885321c0862b50b6b1c3392405";
      flake = false;
    };
    blink-cmp-git = {
      url = "github:Kaiser-Yang/blink-cmp-git/d3f2a9067ab028e779d08e61bf0b054939011316";
      flake = false;
    };
    blink-cmp-spell = {
      url = "github:ribru17/blink-cmp-spell/2bd0e0d5e7735c047e72b6918a0458f3e8fadaba";
      flake = false;
    };
    blink-emoji-nvim = {
      url = "github:moyiz/blink-emoji.nvim/dff709139ad5389fb55ebab026e75278a12b325a";
      flake = false;
    };
    blink-cmp = {
      url = "github:saghen/blink.cmp/78336bc89ee5365633bcf754d93df01678b5c08f";
      flake = false;
    };
    bufresize-nvim = {
      url = "github:kwkarlwang/bufresize.nvim/3b19527ab936d6910484dcc20fb59bdb12322d8b";
      flake = false;
    };
    capture-vim = {
      url = "github:tyru/capture.vim/857ee11cfe1193948d3d45dcb8d511fded8533fb";
      flake = false;
    };
    chowcho-nvim = {
      url = "github:tkmpypy/chowcho.nvim/c87ba3be2059070e16c89bf1710762dd70cb3007";
      flake = false;
    };
    colorful-winsep-nvim = {
      url = "github:nvim-zh/colorful-winsep.nvim/6134b5cd4a38990c7b720adc90973ed32f726179";
      flake = false;
    };
    copilot-lua = {
      url = "github:zbirenbaum/copilot.lua/f76a0a281de089e27b605ec8017093f1aab73b07";
      flake = false;
    };
    crates-nvim = {
      url = "github:saecki/crates.nvim/7039bc1d130e424232a7aa64ceddb170a154ff5b";
      flake = false;
    };
    dial-nvim = {
      url = "github:monaqa/dial.nvim/f2634758455cfa52a8acea6f142dcd6271a1bf57";
      flake = false;
    };
    dropbar-nvim = {
      url = "github:Bekaboo/dropbar.nvim/808ba31cde89aec8833e9789f5e04557cd31c9e1";
      flake = false;
    };
    fileline-nvim = {
      url = "github:lewis6991/fileline.nvim/c116aa8dd7aa7e1db6938f872285e598dc9ee00b";
      flake = false;
    };
    flash-nvim = {
      url = "github:folke/flash.nvim/5f0f270fdc7c5b0c21d903ee85b9cb06f2ac636a";
      flake = false;
    };
    flatten-nvim = {
      url = "github:willothy/flatten.nvim/d92ca41e9c330f45c1b854a80c89c8488a9d730c";
      flake = false;
    };
    git-conflict-nvim = {
      url = "github:akinsho/git-conflict.nvim/4bbfdd92d547d2862a75b4e80afaf30e73f7bbb4";
      flake = false;
    };
    git-rebase-auto-diff-nvim = {
      url = "github:yutkat/git-rebase-auto-diff.nvim/6fd2f5ba63828e5c4fd59bb1b75ef7525a5ce39f";
      flake = false;
    };
    gitignore-nvim = {
      url = "github:wintermute-cell/gitignore.nvim/15ed88abbaeb5deffe6d7c6d51af9b6ff784135f";
      flake = false;
    };
    gitsigns-nvim = {
      url = "github:lewis6991/gitsigns.nvim/a462f416e2ce4744531c6256252dee99a7d34a83";
      flake = false;
    };
    glance-nvim = {
      url = "github:dnlhc/glance.nvim/5a8eab1c1c48bfa19a33b556328a3c553138366e";
      flake = false;
    };
    guess-indent-nvim = {
      url = "github:NMAC427/guess-indent.nvim/84a4987ff36798c2fc1169cbaff67960aed9776f";
      flake = false;
    };
    highlight-undo-nvim = {
      url = "github:tzachar/highlight-undo.nvim/ee32e12693d70e66f954d09a504a7371d110fc27";
      flake = false;
    };
    inc-rename-nvim = {
      url = "github:smjonas/inc-rename.nvim/ddff8bd3eccedf043bd73f5bf89cf90d2d6d8105";
      flake = false;
    };
    kanagawa-nvim = {
      url = "github:rebelot/kanagawa.nvim/8ad3b4cdcc804b332c32db8f9743667e1bb82b99";
      flake = false;
    };
    lsp-format-nvim = {
      url = "github:lukas-reineke/lsp-format.nvim/e2b4ae87545c1aadebcf1dfc1b5dffe28dcf2ffb";
      flake = false;
    };
    mark-code-action-nvim = {
      url = "github:crwebb85/mark-code-action.nvim/7129ba61349bcb03defb5a482aa5677fecca1462";
      flake = false;
    };
    marks-nvim = {
      url = "github:chentoast/marks.nvim/f353e8c08c50f39e99a9ed474172df7eddd89b72";
      flake = false;
    };
    mini-ai = {
      url = "github:echasnovski/mini.ai/bfb26d9072670c3aaefab0f53024b2f3729c8083";
      flake = false;
    };
    mini-extra = {
      url = "github:echasnovski/mini.extra/31f82562238a4fadd30997757ead6c7f1770e7ea";
      flake = false;
    };
    mini-icons = {
      url = "github:echasnovski/mini.icons/e56797f90192d81f1fda02e662fc3e8e3d775027";
      flake = false;
    };
    mini-jump = {
      url = "github:echasnovski/mini.jump/99799e8ca33fe936b81a70b5ab9a081f8794c8a1";
      flake = false;
    };
    mini-move = {
      url = "github:echasnovski/mini.move/4d214202d71e0a4066b6288176bbe88f268f9777";
      flake = false;
    };
    mini-splitjoin = {
      url = "github:echasnovski/mini.splitjoin/9fcd8856efb95a505090c3225726466494076127";
      flake = false;
    };
    mini-surround = {
      url = "github:echasnovski/mini.surround/88c52297ed3e69ecf9f8652837888ecc727a28ee";
      flake = false;
    };
    mini-trailspace = {
      url = "github:echasnovski/mini.trailspace/f8083ca969e1b2098480c10f3c3c4d2ce3586680";
      flake = false;
    };
    mkdir-nvim = {
      url = "github:jghauser/mkdir.nvim/c55d1dee4f099528a1853b28bb28caa802eba217";
      flake = false;
    };
    modes-nvim = {
      url = "github:mvllow/modes.nvim/2badf8771dbb2d1e1066fd6a5dddaad2fc836e72";
      flake = false;
    };
    modesearch-vim = {
      url = "github:monaqa/modesearch.vim/71f123cadbb86e0cbacc12f472d18684fc3308a8";
      flake = false;
    };
    moonbit-nvim = {
      url = "github:moonbit-community/moonbit.nvim/907c8240d3d2f96fa8e8569c73973e8604a7b1e6";
      flake = false;
    };
    noice-nvim = {
      url = "github:folke/noice.nvim/7bfd942445fb63089b59f97ca487d605e715f155";
      flake = false;
    };
    nui-nvim = {
      url = "github:MunifTanjim/nui.nvim/f535005e6ad1016383f24e39559833759453564e";
      flake = false;
    };
    nvim-FeMaco-lua = {
      url = "github:AckslD/nvim-FeMaco.lua/96bbf843595dbe865838b3f2484b73557f34700c";
      flake = false;
    };
    nvim-bqf = {
      url = "github:kevinhwang91/nvim-bqf/c282a62bec6c0621a1ef5132aa3f4c9fc4dcc2c7";
      flake = false;
    };
    nvim-early-retirement = {
      url = "github:chrisgrieser/nvim-early-retirement/d73ddf7b8b776aa917947142873a05f733103757";
      flake = false;
    };
    nvim-highlight-colors = {
      url = "github:brenoprata10/nvim-highlight-colors/e4c7af0211866162d999ce0bdd6a029302e19139";
      flake = false;
    };
    nvim-insx = {
      url = "github:hrsh7th/nvim-insx/fbba86031f3927ecbc11556217b4976a149c29c6";
      flake = false;
    };
    nvim-lightbulb = {
      url = "github:kosayoda/nvim-lightbulb/b8c08c5f3b1586dfcdd9f34d7d54fe6982e01ac9";
      flake = false;
    };
    nvim-lspconfig = {
      url = "github:neovim/nvim-lspconfig/4d363f93c3581b9212a24f7a830d7590b3f050af";
      flake = false;
    };
    nvim-treesitter = {
      url = "github:nvim-treesitter/nvim-treesitter/f603a2f4da48728f80257fb5fbb90145fd1dc173";
      flake = false;
    };
    nvim-treesitter-clipping = {
      url = "github:monaqa/nvim-treesitter-clipping/fa7c052cfcafa73099dbf2c1697dc56557dbde9f";
      flake = false;
    };
    nvim-treesitter-context = {
      url = "github:romgrk/nvim-treesitter-context/b0c45cefe2c8f7b55fc46f34e563bc428ef99636";
      flake = false;
    };
    nvim-treesitter-textobjects = {
      url = "github:nvim-treesitter/nvim-treesitter-textobjects/5c7b0263797dfd1bd6202f2b219f3b53a80b2187";
      flake = false;
    };
    nvim-ts-autotag = {
      url = "github:windwp/nvim-ts-autotag/88c1453db4ba7dd24131086fe51fdf74e587d275";
      flake = false;
    };
    nvim-ts-context-commentstring = {
      url = "github:JoosepAlviste/nvim-ts-context-commentstring/6141a40173c6efa98242dc951ed4b6f892c97027";
      flake = false;
    };
    octo-nvim = {
      url = "github:pwntester/octo.nvim/af2411604b51cb4a0f3e2de50b1b7cacc2581c48";
      flake = false;
    };
    oil-git-status-nvim = {
      url = "github:refractalize/oil-git-status.nvim/a3e2ccb00cb8822115e28a9a1791eda051d940c9";
      flake = false;
    };
    oil-nvim = {
      url = "github:stevearc/oil.nvim/17c0a8faaf48298a0c0cfb0d757c0eaee4ff7a32";
      flake = false;
    };
    other-nvim = {
      url = "github:rgroli/other.nvim/d36a66a";
      flake = false;
    };
    parinfer-rust = {
      url = "github:eraserhd/parinfer-rust";
      flake = false;
    };
    peridot-vim = {
      url = "github:monaqa/peridot.vim/5dda71a487d225c16209617d34acff08afb2d50b";
      flake = false;
    };
    persistence-nvim = {
      url = "github:folke/persistence.nvim/b20b2a7887bd39c1a356980b45e03250f3dce49c";
      flake = false;
    };
    plenary-nvim = {
      url = "github:nvim-lua/plenary.nvim/74b06c6c75e4eeb3108ec01852001636d85a932b";
      flake = false;
    };
    quicker-nvim = {
      url = "github:stevearc/quicker.nvim/4a6883cb13fe097a20a046eb55f6dffd239276e3";
      flake = false;
    };
    rustaceanvim = {
      url = "github:mrcjkb/rustaceanvim/e9c5aaba16fead831379d5f44617547a90b913c7";
      flake = false;
    };
    satellite-nvim = {
      url = "github:lewis6991/satellite.nvim/87843c9c8f28b54332497302de380a6d94c9e82b";
      flake = false;
    };
    schemastore-nvim = {
      url = "github:b0o/schemastore.nvim/12dd0de1f15d598db2cc0d075f4f0d13a3290d4d";
      flake = false;
    };
    snacks-nvim = {
      url = "github:folke/snacks.nvim/882c996cf28183f4d63640de0b4c02ec886d01f2";
      flake = false;
    };
    sort-nvim = {
      url = "github:sQVe/sort.nvim/fa6318fc6676294bff0fd56ae8e8f9552be1ac7e";
      flake = false;
    };
    stickybuf-nvim = {
      url = "github:stevearc/stickybuf.nvim/0c1e5f1a3eb36eea2cea57083828269cc62c58e4";
      flake = false;
    };
    substitute-nvim = {
      url = "github:gbprod/substitute.nvim/0d2077398552f069abccbd964a26dd7cd26882cd";
      flake = false;
    };
    term-edit-nvim = {
      url = "github:chomosuke/term-edit.nvim/b190a91178ef98beefac2ec0823db047978ea327";
      flake = false;
    };
    troublesum-nvim = {
      url = "github:ivanjermakov/troublesum.nvim/b00301bb565bfcb6fcfa41f2012e43a0528da65b";
      flake = false;
    };
    ts-error-translator-nvim = {
      url = "github:dmmulroy/ts-error-translator.nvim/558abff11b9e8f4cefc0de09df780c56841c7a4b";
      flake = false;
    };
    vim-asterisk = {
      url = "github:haya14busa/vim-asterisk/77e97061d6691637a034258cc415d98670698459";
      flake = false;
    };
    vim-illuminate = {
      url = "github:RRethy/vim-illuminate/1cc33d347c574c3bd21a4852fc9ffed677c1c58c";
      flake = false;
    };
    vim-log-highlighting = {
      url = "github:mtdl9/vim-log-highlighting/1037e26f3120e6a6a2c0c33b14a84336dee2a78f";
      flake = false;
    };
    vim-manpager = {
      url = "github:lambdalisue/vim-manpager/ba60d59a79c096775f5c7f7d76fdffa396efdfca";
      flake = false;
    };
    vim-matchup = {
      url = "github:andymass/vim-matchup/0106b1afd4a2f7e1098037b5ceb161bab7471088";
      flake = false;
    };
    vim-partedit = {
      url = "github:thinca/vim-partedit/a4ed06ff7759343d205b4a5be08a5bb49ee878c3";
      flake = false;
    };
    vim-repeat = {
      url = "github:tpope/vim-repeat/65846025c15494983dafe5e3b46c8f88ab2e9635";
      flake = false;
    };
    vim-sonictemplate = {
      url = "github:mattn/vim-sonictemplate/050450414ca69885df7c26936821d74678ff4904";
      flake = false;
    };
    vim-startuptime = {
      url = "github:dstein64/vim-startuptime/5f33e50f1e2e2a80370c9094e4c303ea54cd2aea";
      flake = false;
    };
    vim-table-mode = {
      url = "github:dhruvasagar/vim-table-mode/bb025308a45c67c7c8f0763ba37bc2ee3f534df0";
      flake = false;
    };
    vim-textobj-blockwise = {
      url = "github:osyo-manga/vim-textobj-blockwise/c731da12fbd5728a22fb8d3c800b8bcdcbf94da8";
      flake = false;
    };
    vim-textobj-user = {
      url = "github:kana/vim-textobj-user/41a675ddbeefd6a93664a4dc52f302fe3086a933";
      flake = false;
    };
    vim-visual-multi = {
      url = "github:mg979/vim-visual-multi/a6975e7c1ee157615bbc80fc25e4392f71c344d4";
      flake = false;
    };
    wb-only-current-line-nvim = {
      url = "github:yutkat/wb-only-current-line.nvim/93ebd5eadfee2b0cb911806ce30dc8a798a6a17b";
      flake = false;
    };
    which-key-nvim = {
      url = "github:folke/which-key.nvim/3aab2147e74890957785941f0c1ad87d0a44c15a";
      flake = false;
    };
    winresizer = {
      url = "github:simeji/winresizer/299076f7f79e2e2f7706b2dfacbb3c074ce53257";
      flake = false;
    };
  };
  outputs = _: { };
}
