pcall(vim.cmd.packadd, "impatient")
pcall(require, "impatient")

require("global")
require("base")
require("options")
require("display")
require("plugin")
require("autocmd")
require("keymaps")

vim.defer_fn(function()
  require("command")
  require("vscode")
  require("macos")
end, 0)
