pcall(vim.cmd, [[silent packadd! impatient"]])
pcall(require, "impatient")

require("base")
require("display")
require("options")
require("plugin")
require("autocmd")

vim.defer_fn(function()
  require("keymaps")
  require("command")
  require("vscode")
  require("macos")
end, 0)
