# Onedark Wezterm Colors
# Style: onedark

[colors]
background = "#1e2127"
foreground = "#e6efff"
ansi = [ "#1e2127", "#e06c75", "#98c379", "#d19a66", "#61afef", "#c678dd", "#56b6c2", "#828791" ]
brights = [ "#5c6370", "#e06c75", "#98c379", "#d19a66", "#61afef", "#c678dd", "#56b6c2", "#e6efff" ]
