name: 'CI: Neovim plugins'

on:
  push:
    paths:
      - 'nvim/**'
      - 'flake.nix'
      - '.github/workflows/nix-neovim.yaml'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  neovim-check:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: ./.github/actions/setup-nix

      - name: Check Neovim configuration
        run: nix run .#nvim-restore
        env:
          DOTFILES_DIR: ${{ github.workspace }}
