name: Renovate config linter

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yml
      - renovate.json
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yml
      - renovate.json

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
