name: Renovate config linter

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - .github/renovate.json5
  pull_request:

jobs:
  renovate-validate:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@b850926b611b1f3d3fe3729776339c217834bf2c # v2.2.0
